import 'server-only';
import type { AmazonProduct, Currency, Marketplace, ProductResponse } from './types';
type Config={name:string;domain:string;tag:string;currency:Currency;locale:string;searches:string[]};
export const MARKETPLACES:Record<Marketplace,Config>={
 de:{name:'Germany',domain:'www.amazon.de',tag:'Onlinestarkei-21',currency:'EUR',locale:'de_DE',searches:['Anlagegold Feingold','Goldbarren 999,9','Goldbarren 1g 2g 5g','Goldbarren 10g 20g','Goldbarren 1 oz 50g','Goldbarren 100g 250g','Goldmünze Feingold','Krügerrand Maple Leaf Britannia Gold']},
 us:{name:'United States',domain:'www.amazon.com',tag:'goldfindercom-20',currency:'USD',locale:'en_US',searches:['investment gold bullion','999.9 gold bars','1 gram 5 gram gold bar','10 gram 20 gram gold bar','1 oz gold bar','gold bullion coins','Krugerrand Maple Leaf Britannia gold coin']},
 uk:{name:'United Kingdom',domain:'www.amazon.co.uk',tag:'goldfindercom-21',currency:'GBP',locale:'en_GB',searches:['investment gold bullion','999.9 gold bars','1 gram 5 gram gold bar','10 gram 20 gram gold bar','1 oz gold bar','gold bullion coins','Krugerrand Maple Leaf Britannia gold coin']}
};
const TOKEN_URL='https://api.amazon.co.uk/auth/o2/token',SEARCH_URL='https://creatorsapi.amazon/catalog/v1/searchItems',CACHE_MS=30*60*1000;
const ALLOWED_IMAGES=new Set(['m.media-amazon.com','images-na.ssl-images-amazon.com','images-eu.ssl-images-amazon.com']);
const AVAILABLE=new Set(['IN_STOCK','INSTOCK','INSTOCKSCARCE','LEADTIME']);
const EXCLUDED=/vergoldet|goldfarben|gold farben|plattiert|gold plated|replica|replik|nachprägung|medaille|münzkapsel|capsule|sammlerbox|geschenkbox|gift box|foil|blattgold|jewelry|jewellery|schmuck|pendant|anhänger|necklace|kette|ring|earring|ohrring|bracelet|armband/i;
const GOLD_PRODUCT=/gold bar|gold bullion|gold coin|goldbarren|feingold|goldmünze|krügerrand|krugerrand|maple leaf|britannia|philharmoniker|kangaroo|känguru|gold nugget/i;
const caches=new Map<Marketplace,{until:number;data:ProductResponse}>();let tokenCache:{until:number;value:string}|undefined;
const pick=(value:unknown,path:string):any=>path.split('.').reduce<any>((current,key)=>current?.[key],value);
function validImage(value?:string){try{return Boolean(value&&ALLOWED_IMAGES.has(new URL(value).hostname));}catch{return false;}}
function withTimeout(url:string,init:RequestInit,timeout=8000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeout);return fetch(url,{...init,signal:controller.signal,cache:'no-store'}).finally(()=>clearTimeout(timer));}
async function accessToken(){if(tokenCache&&tokenCache.until>Date.now())return tokenCache.value;const clientId=process.env.AMAZON_CREATORS_CLIENT_ID,clientSecret=process.env.AMAZON_CREATORS_CLIENT_SECRET;if(!clientId||!clientSecret)throw new Error('credentials_missing');const response=await withTimeout(TOKEN_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({grant_type:'client_credentials',client_id:clientId,client_secret:clientSecret,scope:'creatorsapi::default'})});if(!response.ok)throw new Error(`token_${response.status}`);const body=await response.json();if(!body.access_token)throw new Error('token_missing');tokenCache={value:body.access_token,until:Date.now()+Math.max(60,Number(body.expires_in||3600)-120)*1000};return tokenCache.value;}
function normalize(item:any,c:Config):AmazonProduct|null{const asin=String(item?.asin||'').toUpperCase(),parentAsin=String(item?.parentASIN||asin).toUpperCase(),title=String(pick(item,'itemInfo.title.displayValue')||'').trim();const features=(pick(item,'itemInfo.features.displayValues')||[]).filter((v:unknown):v is string=>typeof v==='string'),searchable=`${title} ${features.join(' ')}`,image=[pick(item,'images.primary.hiRes.url'),pick(item,'images.primary.large.url'),pick(item,'images.primary.medium.url')].find(validImage),listing=item?.offersV2?.listings?.find((entry:any)=>AVAILABLE.has(String(entry?.availability?.type||'').replaceAll('_','').toUpperCase()));if(!/^[A-Z0-9]{10}$/.test(asin)||!title||!image||!listing||!GOLD_PRODUCT.test(searchable)||EXCLUDED.test(searchable))return null;const money=listing?.price?.money,brand=String(pick(item,'itemInfo.byLineInfo.brand.displayValue')||pick(item,'itemInfo.byLineInfo.manufacturer.displayValue')||'Not specified'),model=String(pick(item,'itemInfo.manufactureInfo.model.displayValue')||pick(item,'itemInfo.productInfo.size.displayValue')||title);const product:AmazonProduct={asin,parentAsin,brand,model,title,image,available:true,availability:String(listing.availability.message||'Available'),features,detailPageUrl:`https://${c.domain}/dp/${asin}?tag=${c.tag}`,fetchedAt:new Date().toISOString()};if(typeof money?.amount==='number'&&money.currency===c.currency)product.price={amount:money.amount,currency:c.currency,display:String(money.displayAmount||new Intl.NumberFormat(c.locale.replace('_','-'),{style:'currency',currency:c.currency}).format(money.amount)),source:'amazon-creators-api'};return product;}
async function search(access:string,keywords:string,itemPage:number,c:Config){const response=await withTimeout(SEARCH_URL,{method:'POST',headers:{authorization:`Bearer ${access}`,'content-type':'application/json','x-marketplace':c.domain},body:JSON.stringify({keywords,itemCount:10,itemPage,searchIndex:'All',availability:'Available',currencyOfPreference:c.currency,languagesOfPreference:[c.locale],marketplace:c.domain,partnerTag:c.tag.toLowerCase(),resources:['images.primary.large','itemInfo.title','itemInfo.features','itemInfo.byLineInfo','itemInfo.manufactureInfo','itemInfo.productInfo','offersV2.listings.price','offersV2.listings.availability','parentASIN']})});if(!response.ok)throw new Error(`search_${response.status}_${(await response.text()).slice(0,160)}`);const body=await response.json();return(body?.searchResult?.items||[]).map((item:any)=>normalize(item,c)).filter(Boolean) as AmazonProduct[];}
function deduplicate(products:AmazonProduct[]){const unique=new Map<string,AmazonProduct>();for(const product of products){const key=product.parentAsin||`${product.brand}|${product.model}`.toLowerCase(),current=unique.get(key);if(!current||(!current.price&&product.price))unique.set(key,product);}return[...unique.values()].sort((a,b)=>(a.price?.amount??Infinity)-(b.price?.amount??Infinity));}
export async function getAmazonProducts(marketplace:Marketplace):Promise<ProductResponse>{const c=MARKETPLACES[marketplace],base={marketplace,marketplaceName:c.name,amazonDomain:c.domain,currency:c.currency,locale:c.locale},cached=caches.get(marketplace);if(cached&&cached.until>Date.now())return cached.data;try{const access=await accessToken(),found:AmazonProduct[]=[];for(const keywords of c.searches)for(const page of[1,2]){found.push(...await search(access,keywords,page,c));await new Promise(resolve=>setTimeout(resolve,1050));}const products=deduplicate(found),data:ProductResponse={...base,products,count:products.length,live:true,fetchedAt:new Date().toISOString()};caches.set(marketplace,{until:Date.now()+CACHE_MS,data});return data;}catch(error){console.error(`Amazon ${marketplace} unavailable:`,error instanceof Error?error.message:'unknown');return{...base,products:[],count:0,live:false,fetchedAt:null,message:error instanceof Error&&error.message==='credentials_missing'?'Live Amazon products are not configured yet.':marketplace==='de'?'Amazon live products are temporarily unavailable. No cached prices are being shown.':'Amazon has not yet enabled this marketplace for the connected Creators API account. No prices or fallback products are being shown.'};}}
export {ALLOWED_IMAGES};
