import data from '@/data/manufacturer-products.json';
import {markets,regions,origin,type Region,type Copy,products,type Product} from './product-catalogue';
export const manufacturerProducts=data;
export type ManufacturerProduct=typeof data[number];
export function manufacturerPath(p:ManufacturerProduct,r:Region){return `${r==='global'?'':`/${r}`}/${r==='de'?'produkt':r==='fr'?'produit':'product'}/${p.slug}`;}
export const manufacturerPages=regions.flatMap(region=>manufacturerProducts.map(product=>({product,region,path:manufacturerPath(product,region)})));
export function findManufacturerPage(path:string){return manufacturerPages.find(p=>p.path===path);}
export function manufacturerAlternates(p:ManufacturerProduct){return Object.fromEntries([...regions.map(r=>[markets[r].hreflang,`${origin}${manufacturerPath(p,r)}`]),['x-default',`${origin}${manufacturerPath(p,'global')}`]]);}
export function productFamily(p:ManufacturerProduct):Product|undefined{return p.grams&&p.packaging!=='collection'&&p.packaging!=='proof'?products.find(x=>x.kind==='bar'&&Math.abs(x.grams-p.grams!)<.01):undefined;}
export const packageCopy:Record<string,Copy>={
 mini:{de:'Dieses Kleinstformat ist deutlich leichter als ein 1-g-Barren. Vergleiche den Preis deshalb über das tatsächliche Grammgewicht; die Präsentation kann einen erheblichen Anteil am Kaufpreis ausmachen. Ein kleiner Gesamtpreis bedeutet nicht automatisch ein niedriges Aufgeld.',en:'This miniature format is substantially lighter than a 1 g bar. Compare using its actual gram weight; presentation can account for a substantial part of the price. A low total price does not automatically mean a low premium.',fr:'Ce petit format est nettement plus léger qu’un lingotin de 1 g. Comparez à partir du poids réel en grammes ; la présentation peut représenter une part importante du prix. Un faible prix total ne signifie pas automatiquement une faible prime.'},
 goldcard:{de:'Die Goldcard ist Teil der Präsentation dieser Sammlerausgabe. Für einen Vergleich mit Standardbarren fehlen im Referenzdatensatz genaue Gewichtsangaben. Lass dir vor dem Kauf Feingoldgewicht und den vollständigen Lieferumfang bestätigen.',en:'The gold card is part of the presentation of this collector issue. The reference record does not specify enough weight information for a like-for-like comparison with standard bars. Confirm fine-gold weight and the complete contents before purchase.',fr:'La carte fait partie de la présentation de cette édition de collection. La fiche de référence ne précise pas suffisamment le poids pour une comparaison avec des lingotins standards. Faites confirmer le poids d’or fin et le contenu exact avant l’achat.'},
 coincard:{de:'Die Coincard präsentiert das Motiv zusammen mit dem Goldprodukt. Prüfe, ob Bild, Goldobjekt und Zertifikat eigenständige Bestandteile sind. Der Kartenname sagt nichts über den Feingoldanteil aus; dafür werden Gewicht und Feinheit der konkreten Ausgabe benötigt.',en:'The coin card presents the theme alongside the gold item. Check whether the artwork, gold object and certificate are separate components. The card’s name does not establish fine-gold content; that requires the exact issue’s weight and fineness.',fr:'La coincard présente le thème avec l’objet en or. Vérifiez si l’illustration, l’objet et le certificat sont des éléments distincts. Le nom de la carte ne détermine pas la quantité d’or fin ; il faut connaître le poids et le titre de l’émission précise.'},
 gift:{de:'Dieses Angebot kombiniert das Goldprodukt mit einer Geschenkpräsentation. Vergleiche es zusätzlich mit derselben Goldmenge ohne Geschenkzubehör. Prüfe Grußkarte, Umschlag und Zertifikat im Lieferumfang; eine Verkäufergarantie ist von einem Herstellerzertifikat zu unterscheiden.',en:'This listing combines the gold item with gift presentation. Compare it with the same amount of gold without gift accessories. Check the card, envelope and certificate included; distinguish a seller’s guarantee from a manufacturer’s certificate.',fr:'Cette offre associe un produit en or à une présentation cadeau. Comparez-la avec la même quantité d’or sans accessoires. Vérifiez la carte, l’enveloppe et le certificat inclus ; distinguez une garantie du vendeur d’un certificat du fabricant.'},
 pouch:{de:'Der Geschenkbeutel ergänzt die schützende Produktverpackung. Er erhöht nicht das Goldgewicht. Kontrolliere, ob Kapsel, Grußkarte und Garantie tatsächlich mitgeliefert werden, und bewahre die Angaben zur Herkunft zusammen mit der Rechnung auf.',en:'The gift pouch supplements the protective product packaging. It does not increase gold weight. Check which capsule, greeting card and guarantee are actually included, and keep provenance details with the invoice.',fr:'La pochette cadeau complète l’emballage de protection. Elle n’augmente pas le poids d’or. Vérifiez la présence de la capsule, de la carte et de la garantie, puis conservez les informations de provenance avec la facture.'},
 box:{de:'Bei einer Motivbox ist das Design ein eigener Teil des Angebots. Vergleiche Gewicht und Feinheit unabhängig vom Anlass oder Motiv. Eine aufklappbare Geschenkbox ist nicht automatisch eine manipulationssichere Originalverpackung des Raffineurs.',en:'A themed presentation box adds a design component to the offer. Compare weight and fineness independently of the occasion or artwork. An opening gift box is not automatically the refiner’s tamper-evident original packaging.',fr:'Le coffret illustré ajoute un élément décoratif à l’offre. Comparez le poids et le titre indépendamment de l’occasion ou du motif. Un coffret ouvrant n’est pas automatiquement un conditionnement inviolable d’origine de l’affineur.'},
 blister:{de:'Bei einem Blisterangebot gehören Zustand und Originalität der Verpackung zum Vergleich. Prüfe, ob eine vorhandene Seriennummer auf Barren und Verpackung übereinstimmt. Nicht jeder Barren jeder Größe trägt zwingend eine individuelle Nummer.',en:'For a blister-pack listing, packaging condition and originality are part of the comparison. If serial numbers are supplied on both bar and packaging, check that they match. Not every bar of every size necessarily has an individual number.',fr:'Pour une offre sous blister, l’état et l’origine de l’emballage font partie de la comparaison. Si des numéros de série figurent sur le lingotin et le conditionnement, vérifiez leur concordance. Tous les formats ne portent pas nécessairement un numéro individuel.'},
 proof:{de:'Die Sammlerausführung stellt Motiv und Erhaltung neben den Metallwert. Oberflächen sollten nicht gereinigt oder unnötig berührt werden. Ein Aufpreis für die Ausführung ist kein zugesicherter späterer Sammlerwert; prüfe Jahrgang, Stückelung und Etui im konkreten Angebot.',en:'A collector finish makes design and condition part of the comparison alongside metal value. Avoid cleaning or unnecessary handling of the surface. A finish premium does not guarantee future collectible value; check the year, denomination and case in the listing.',fr:'Une finition de collection ajoute le motif et l’état à la comparaison de la valeur métallique. Évitez le nettoyage et les manipulations inutiles. Une prime de finition ne garantit pas une valeur de collection future ; vérifiez millésime, fraction et écrin.'},
 card:{de:'Die Produktkarte dient der Präsentation und kann Identifikationsangaben enthalten. Gleiche Kartenbezeichnung und Barrenkennzeichnung mit dem konkreten Angebot ab. Bewahre die Einheit möglichst zusammen auf und prüfe, welche Angaben direkt vom Hersteller stammen.',en:'The product card presents the item and may include identification details. Match the card designation and bar markings to the specific listing. Keep the unit together where practical and check which information originates from the manufacturer.',fr:'La carte présente le produit et peut porter des informations d’identification. Comparez sa désignation et les inscriptions du lingotin à l’offre précise. Conservez l’ensemble si possible et vérifiez quelles indications proviennent du fabricant.'},
 split:{de:'Hier wird die Goldmenge auf mehrere Teilstücke verteilt. Vergleiche die Gesamtmenge und die Anzahl einzeln nutzbarer Einheiten. Ein Set oder eine Goldtafel mit gleichem Gesamtgewicht ist nicht dasselbe Produkt wie ein massiver Einzelbarren; Verpackung und Aufgeld können abweichen.',en:'Here the gold amount is distributed across separate units. Compare total weight and the number of independently usable pieces. A set or divisible sheet is not the same product as a solid bar of the same total weight; packaging and premiums can differ.',fr:'La quantité d’or est ici répartie en plusieurs éléments. Comparez le poids total et le nombre d’unités utilisables séparément. Un lot ou une plaquette divisible n’est pas le même produit qu’un lingot massif de poids équivalent ; emballage et prime peuvent différer.'},
 case:{de:'Das Etui oder der Mini-Koffer gehört zum Geschenkcharakter dieses Angebots. Seine Größe ist nicht die Größe des Goldbarrens. Vergleiche die Metallmenge separat und prüfe, welche zusätzliche Schutzverpackung das Gold selbst umgibt.',en:'The case or miniature suitcase is part of the gift presentation. Its dimensions are not the dimensions of the gold bar. Compare the metal amount separately and check the protective packaging around the gold itself.',fr:'L’écrin ou la mini-mallette fait partie de la présentation cadeau. Ses dimensions ne sont pas celles du lingotin. Comparez séparément la quantité de métal et vérifiez la protection qui entoure l’or lui-même.'},
 kinebar:{de:'Die Kinebar-Ausführung besitzt ein optisches Sicherheitsmerkmal. Dieses Merkmal ist von einer bloßen Verpackungsabbildung zu unterscheiden. Prüfe die genaue Herstellerbezeichnung, die Gewichtsvariante und den beschriebenen Lieferumfang; das Motiv allein belegt keine Echtheit.',en:'The Kinebar version includes an optical security feature. Distinguish that feature from a picture on the packaging. Check the exact manufacturer designation, weight variant and contents; the design alone is not proof of authenticity.',fr:'La version Kinebar comporte un dispositif optique de sécurité. Distinguez ce dispositif d’une simple image sur l’emballage. Vérifiez le fabricant exact, le poids choisi et le contenu ; le motif seul ne prouve pas l’authenticité.'},
 collection:{de:'Das Set umfasst sieben sehr kleine Einzelmünzen. Addiere deren Feingoldgewichte, statt die Anzahl der Münzen mit einer größeren Goldmenge gleichzusetzen. Die Kassette und die zusammengehörenden Motive können einen eigenen Teil des Aufpreises ausmachen.',en:'The set contains seven very small individual coins. Add their fine-gold weights rather than equating the coin count with a large gold amount. The case and coordinated designs can account for a separate part of the premium.',fr:'Le coffret contient sept très petites pièces. Additionnez leurs poids d’or fin plutôt que d’associer le nombre de pièces à une grande quantité d’or. La cassette et les motifs coordonnés peuvent représenter une part distincte de la prime.'},
 variants:{de:'Der Referenztitel nennt mehrere wählbare Gewichte. Ohne ausgewählte Variante gibt es deshalb kein eindeutig festgelegtes Gesamtgewicht. Prüfe im Warenkorb die Auswahl 3 g, 5 g oder 10 g und vergleiche erst danach Preis und Lieferumfang.',en:'The reference title lists several selectable weights. There is therefore no single fixed total weight until a variant is selected. Confirm the 3 g, 5 g or 10 g choice in the cart before comparing price and contents.',fr:'Le titre de référence mentionne plusieurs poids au choix. Le poids total n’est donc pas unique tant qu’une variante n’est pas sélectionnée. Confirmez le choix de 3 g, 5 g ou 10 g dans le panier avant de comparer le prix et le contenu.'},
 standard:{de:'Vergleiche die genaue Hersteller- und Gewichtsbezeichnung mit gleichartigen Barren. Händlertexte können Maße der Versandverpackung oder alternative Varianten enthalten. Maßgeblich sind die Spezifikationen des konkret ausgewählten Barrens, nicht pauschale Werbeversprechen.',en:'Compare the exact manufacturer and weight designation with equivalent bars. Seller descriptions may include shipping-package dimensions or alternative variants. Use the selected bar’s specifications rather than broad promotional claims.',fr:'Comparez la désignation exacte du fabricant et du poids avec des lingotins équivalents. Les descriptifs peuvent inclure les dimensions d’expédition ou d’autres variantes. Retenez les caractéristiques du produit choisi, sans vous fier aux promesses publicitaires générales.'}
};
export function manufacturerSource(p:ManufacturerProduct){
 if(p.slug.startsWith('argor-heraeus'))return{name:'Argor-Heraeus — Bars',url:'https://argor-heraeus.com/bars-coins',text:{de:'Argor-Heraeus unterscheidet klassische geprägte Barren und Kinebar-Ausführungen. Prüfe daher neben dem Gewicht auch die Modellbezeichnung; zwei Barren desselben Herstellers können unterschiedliche Oberflächen und Verpackungen haben.',en:'Argor-Heraeus distinguishes classic minted bars from Kinebar versions. Check the model designation as well as weight: two bars from the same refiner can have different finishes and packaging.',fr:'Argor-Heraeus distingue les lingotins frappés classiques des versions Kinebar. Vérifiez le modèle autant que le poids : deux lingotins du même affineur peuvent présenter des finitions et conditionnements différents.'}};
 if(p.slug.startsWith('heraeus'))return{name:'Heraeus — Gold bars',url:'https://www.heraeus-gold.de/gold/',text:{de:'Heraeus führt verschiedene Barrengrößen und Kinebar-Ausführungen. Der Name Heraeus allein legt die konkrete Variante nicht fest. Gleiche die Barrenprägung mit der offiziellen Produktdarstellung ab; Geschenkverpackungen können vom Händler ergänzt sein.',en:'Heraeus offers different bar sizes and Kinebar versions. The Heraeus name alone does not identify the exact variant. Match the bar markings to the official presentation; gift packaging may be supplied separately by the seller.',fr:'Heraeus propose plusieurs poids et des versions Kinebar. Le nom Heraeus ne suffit pas à identifier la variante exacte. Comparez les inscriptions du lingotin à la présentation officielle ; le conditionnement cadeau peut être ajouté par le vendeur.'}};
 if(p.slug.startsWith('c-hafner'))return{name:'C.HAFNER — Feingoldbarren',url:'https://www.c-hafner.de/produkte-leistungen/feingoldbarren.html',text:{de:'C.HAFNER nennt 1 g und 2 g innerhalb seines geprägten Barrensortiments und beschreibt die CertiCard als Verpackung. Unterscheide diese Herstellerverpackung von Grußkarten oder Geschenkumschlägen eines Händlers.',en:'C.HAFNER lists 1 g and 2 g in its minted-bar range and describes CertiCard packaging. Distinguish the manufacturer’s packaging from greeting cards or gift envelopes supplied by a seller.',fr:'C.HAFNER inclut les formats de 1 g et 2 g dans sa gamme frappée et décrit le conditionnement CertiCard. Distinguez cet emballage du fabricant des cartes de vœux et enveloppes ajoutées par le vendeur.'}};
 if(p.slug.startsWith('perth-mint'))return{name:'The Perth Mint — Kangaroo 5 g',url:'https://www.perthmint.com/shop/themes/animals/kangaroo/kangaroo-5g-minted-gold-bar/',text:{de:'Die Perth Mint beschreibt den 5-g-Barren mit Schwanenlogo auf der Vorderseite und stilisierten Kängurus auf der Rückseite. Das Känguru-Motiv bezeichnet hier einen Barren, nicht automatisch eine australische Goldmünze.',en:'The Perth Mint describes its 5 g bar with a swan logo on the front and stylised kangaroos on the back. The kangaroo design here identifies a bar, not automatically an Australian gold coin.',fr:'La Perth Mint décrit son lingotin de 5 g avec un cygne au recto et des kangourous stylisés au verso. Le motif kangourou désigne ici un lingotin, pas automatiquement une pièce d’or australienne.'}};
 if(p.slug.includes('combibar')||p.slug.includes('5x1')||p.slug.includes('10x1'))return{name:'ESG — CombiBar product range',url:'https://www.combibar.com/products/',text:{de:'Die CombiBar-Produktfamilie umfasst teilbare Edelmetallprodukte. Prüfe, ob das Angebot eine vollständige Tafel, einzelne abgetrennte Segmente oder ein daraus zusammengestelltes Geschenkset beschreibt. Der Markenname allein sagt nichts über die enthaltene Gesamtmenge.',en:'The CombiBar family includes divisible precious-metal products. Check whether the offer contains a complete sheet, detached segments or a gift set assembled from them. The brand name alone does not establish the total metal amount.',fr:'La gamme CombiBar comprend des produits divisibles en métaux précieux. Vérifiez si l’offre contient une plaquette complète, des segments détachés ou un coffret assemblé. Le nom seul ne détermine pas la quantité totale de métal.'}};
 return undefined;
}
