export type Language = 'de' | 'en' | 'fr';
export type Region = 'global' | 'de' | 'fr' | 'us' | 'uk';
export type Copy = Record<Language, string>;
export const origin = 'https://www.gold-finder.com';
export const reviewed = '2026-10-03';
export const markets = {
 global: {label:'International · English', language:'en', hreflang:'en', currency:'USD', locale:'en-US', hub:'/products', country:'International'},
 de: {label:'Deutschland · Deutsch', language:'de', hreflang:'de-DE', currency:'EUR', locale:'de-DE', hub:'/de/produkte', country:'Deutschland'},
 fr: {label:'France · Français', language:'fr', hreflang:'fr-FR', currency:'EUR', locale:'fr-FR', hub:'/fr/produits', country:'France'},
 us: {label:'United States · English', language:'en', hreflang:'en-US', currency:'USD', locale:'en-US', hub:'/us/products', country:'USA'},
 uk: {label:'United Kingdom · English', language:'en', hreflang:'en-GB', currency:'GBP', locale:'en-GB', hub:'/uk/products', country:'UK'},
} as const;
export const regions = Object.keys(markets) as Region[];
export type Product = {id:string; kind:'bar'|'coin'; grams:number; size:string; name:Copy; detail:Copy; comparison:Copy; source:{name:string;url:string}; query:Copy; legacy?:string;};
const mintBars={name:'The Royal Mint — Gold bars',url:'https://www.royalmint.com/invest/bullion/bullion-bars/gold-bars/'};
const barRows:[string,number,string,Copy][]=[
 ['1-g',1,'1 g',{de:'Zehn einzelne 1-g-Barren lassen sich in zehn Schritten verkaufen. Ein 10-g-Barren bündelt dieselbe Gewichtsmenge in einer Einheit. Bei Kleinstbarren wirken sich Verpackung und Herstellung je Gramm besonders stark aus.',en:'Ten separate 1 g bars allow ten separate sales. A single 10 g bar groups the same stated weight into one unit. Packaging and fabrication matter especially when comparing the cost per gram of very small bars.',fr:'Dix lingotins de 1 g peuvent être revendus séparément, contrairement à un seul lingotin de 10 g. Pour ce petit format, la fabrication et le conditionnement pèsent davantage dans le coût par gramme.'}],
 ['2-5-g',2.5,'2.5 g',{de:'Vier Barren zu 2,5 g ergeben 10 g. Gegenüber zehn 1-g-Barren reduziert sich die Anzahl der Einzelstücke; gegenüber einem 5-g-Barren halbiert sich das Gewicht pro Einheit. Prüfe ausdrücklich 2,5 g statt 2 g.',en:'Four 2.5 g bars add up to 10 g. This reduces the number of pieces compared with ten 1 g bars while halving the unit weight of a 5 g bar. Confirm that the listing specifies 2.5 g rather than 2 g.',fr:'Quatre lingotins de 2,5 g représentent 10 g. Ce format réduit le nombre de pièces par rapport à dix lingotins de 1 g et représente la moitié du poids d’un lingotin de 5 g. Vérifiez bien la mention 2,5 g, et non 2 g.'}],
 ['2-g',2,'2 g',{de:'Fünf 2-g-Barren ergeben 10 g. Diese Stückelung liegt zwischen 1 g und 2,5 g und ist nicht mit einem Set aus zwei 1-g-Barren gleichzusetzen. Prüfe, ob das Angebot einen einzelnen Barren oder mehrere Teilstücke enthält.',en:'Five 2 g bars add up to 10 g. This denomination sits between 1 g and 2.5 g and is not the same as a set of two 1 g bars. Check whether the listing supplies a single bar or several separate pieces.',fr:'Cinq lingotins de 2 g représentent 10 g. Ce format se situe entre 1 g et 2,5 g et ne doit pas être confondu avec un lot de deux lingotins de 1 g. Vérifiez si l’offre comprend une seule pièce ou plusieurs éléments.'}],
 ['5-g',5,'5 g',{de:'Zwei 5-g-Barren ergeben 10 g und ermöglichen zwei getrennte Verkäufe. Ein einzelner 10-g-Barren benötigt dagegen nur eine Verpackung. Vergleiche beide Möglichkeiten einschließlich Versand für insgesamt 10 g.',en:'Two 5 g bars total 10 g and allow two separate sales. A single 10 g bar needs only one package. Compare both arrangements including delivery for the same total of 10 g.',fr:'Deux lingotins de 5 g représentent 10 g et permettent deux reventes distinctes. Un lingotin de 10 g ne nécessite qu’un conditionnement. Comparez le coût total livré pour la même quantité de 10 g.'}],
 ['10-g',10,'10 g',{de:'Ein 10-g-Barren ist doppelt so schwer wie ein 5-g-Barren und halb so schwer wie ein 20-g-Barren. Zwei 5-g-Barren bieten dieselbe Gewichtsmenge bei größerer Teilbarkeit. Der 10-g-Barren muss bei einem Verkauf normalerweise als Ganzes abgegeben werden.',en:'A 10 g bar weighs twice as much as a 5 g bar and half as much as a 20 g bar. Two 5 g bars offer the same stated weight with greater flexibility. A standard 10 g bar normally has to be sold as one whole item.',fr:'Un lingotin de 10 g pèse deux fois plus qu’un lingotin de 5 g et deux fois moins qu’un lingotin de 20 g. Deux lingotins de 5 g offrent davantage de souplesse à la revente. Un lingotin classique de 10 g se revend normalement en une seule pièce.'}],
 ['20-g',20,'20 g',{de:'20 g liegen 11,1035 g unter einer Feinunze. Der niedrigere Stückpreis gegenüber 1 oz ist deshalb allein kein Beleg für ein günstigeres Angebot. Zwei 10-g-Barren lassen sich hingegen getrennt veräußern.',en:'20 g is 11.1035 g below one troy ounce. A lower ticket price than a 1 oz bar therefore does not by itself mean a cheaper offer. Two 10 g bars provide the same stated weight in separately sellable pieces.',fr:'20 g représentent 11,1035 g de moins qu’une once troy. Un prix à la pièce inférieur à celui d’un lingot d’une once ne suffit donc pas à établir qu’une offre est plus avantageuse. Deux lingotins de 10 g peuvent être revendus séparément.'}],
 ['1-oz',31.1035,'1 oz',{de:'Bei Anlagegold steht oz für die Feinunze mit rund 31,1035 g. Sie unterscheidet sich von der gewöhnlichen Unze mit rund 28,3495 g. Vergleiche einen 1-oz-Barren mit einer 1-oz-Münze über den ausgewiesenen Feingoldanteil.',en:'Gold uses the troy ounce, approximately 31.1035 g, rather than the everyday ounce of approximately 28.3495 g. Compare a 1 oz bar with a 1 oz bullion coin using declared fine-gold content, not necessarily gross weight.',fr:'L’or se mesure en onces troy, soit environ 31,1035 g, et non en onces ordinaires d’environ 28,3495 g. Pour comparer un lingot et une pièce d’une once, utilisez la teneur en or fin déclarée, pas nécessairement le poids brut.'}],
 ['50-g',50,'50 g',{de:'Ein 50-g-Barren entspricht fünf 10-g-Barren. Die größere Einheit verringert die Zahl der aufzubewahrenden Stücke, lässt aber keinen Verkauf von nur 10 g zu. 50 g sind mehr als eine Feinunze und weniger als zwei.',en:'One 50 g bar equals five 10 g bars in stated weight. The larger unit reduces the number of pieces to store but cannot be partially sold as 10 g. Fifty grams is more than one troy ounce and less than two.',fr:'Un lingot de 50 g équivaut à cinq lingotins de 10 g en poids déclaré. Il réduit le nombre de pièces à conserver, mais ne permet pas de revendre seulement 10 g. 50 g représentent plus d’une once troy et moins de deux.'}],
 ['100-g',100,'100 g',{de:'100 g entsprechen zehn 10-g-Barren oder zwei 50-g-Barren. Ein einziger Barren vereinfacht die Stückzahl, konzentriert aber auch den Betrag pro Verkauf. Prüfe gegossene und geprägte Ausführungen getrennt, da Oberfläche und Verpackung abweichen können.',en:'100 g equals ten 10 g bars or two 50 g bars. A single bar reduces the piece count but also concentrates the value of each resale. Compare cast and minted versions separately because finish and packaging can differ.',fr:'100 g correspondent à dix lingotins de 10 g ou à deux lingots de 50 g. Une seule pièce simplifie le stockage mais concentre la valeur de chaque revente. Comparez séparément les versions coulées et frappées, dont la finition et le conditionnement peuvent varier.'}],
 ['250-g',250,'250 g',{de:'Vier 250-g-Barren ergeben ein Kilogramm. Diese Aufteilung erlaubt spätere Verkäufe in Viertelkilogramm-Schritten. Ein 250-g-Barren entspricht außerdem fünf 50-g-Barren; vergleiche die tatsächlich benötigte Verkaufsgröße.',en:'Four 250 g bars make one kilogram, allowing later sales in quarter-kilogram steps. One 250 g bar also equals five 50 g bars. Compare the resale unit you actually want rather than focusing only on fewer pieces.',fr:'Quatre lingots de 250 g représentent un kilogramme et permettent des reventes par quarts de kilogramme. Un lingot de 250 g équivaut aussi à cinq lingots de 50 g. Comparez la taille de revente souhaitée, et pas uniquement le nombre de pièces.'}],
 ['500-g',500,'500 g',{de:'Zwei 500-g-Barren ergeben ein Kilogramm und können getrennt verkauft werden. Gegenüber fünf 100-g-Barren ist die Teilbarkeit geringer. Kläre vor einer Bestellung die Versicherungssumme pro Sendung sowie die Bedingungen einer persönlichen Übergabe.',en:'Two 500 g bars make one kilogram and can be sold independently. They offer less flexibility than five 100 g bars per half-kilogram. Before ordering, establish the insured limit per shipment and any collection requirements.',fr:'Deux lingots de 500 g représentent un kilogramme et peuvent être revendus séparément. La souplesse est moindre qu’avec cinq lingots de 100 g par demi-kilogramme. Avant de commander, vérifiez le plafond d’assurance par envoi et les modalités de remise.'}],
 ['1-kg',1000,'1 kg',{de:'Ein Kilobarren entspricht zehn 100-g-Barren oder zwei 500-g-Barren. Er bündelt die gesamte Menge in einem Stück. Für kleinere Teilverkäufe sind getrennte Einheiten erforderlich; kläre auch Prüfverfahren und Ankaufbedingungen des späteren Käufers.',en:'A kilogram bar equals ten 100 g bars or two 500 g bars. It concentrates the full amount in one item. Smaller partial sales require separate units; also establish the testing process and buyback terms of a prospective buyer.',fr:'Un lingot d’un kilogramme équivaut à dix lingots de 100 g ou à deux lingots de 500 g. Toute la quantité est réunie en une pièce. Des unités séparées sont nécessaires pour des reventes partielles ; renseignez-vous aussi sur les contrôles et conditions de rachat.'}],
];
export const products:Product[]=barRows.map(([id,grams,size,comparison])=>({id:`bar-${id}`,kind:'bar',grams,size,name:{de:`Goldbarren ${size.replace('.',',')}`,en:`${size} gold bar`,fr:`${grams<50?'Lingotin':'Lingot'} d’or ${size.replace('.',',')}`},detail:{de:`Bei ${size.replace('.',',')}-Goldbarren sind Gewicht, Feingehalt und Hersteller die Ausgangspunkte für den Vergleich. Die Größe allein legt weder die Feinheit noch den aktuellen Verkaufspreis fest.`,en:`For a ${size} gold bar, declared weight, fineness and refiner are the starting points for comparison. Size alone does not determine purity or the current selling price.`,fr:`Pour un format de ${size.replace('.',',')}, le poids déclaré, le titre et l’affineur sont les premiers critères de comparaison. Le poids seul ne détermine ni la pureté ni le prix de vente actuel.`},comparison,source:mintBars,query:{de:`Goldbarren ${size}`,en:`${size} gold bar`,fr:`lingot or ${size}`},legacy:['1-g','5-g','10-g','20-g','1-oz'].includes(id)?`/de/goldbarren/${id}`:undefined}));
const coins:Omit<Product,'kind'|'grams'|'size'|'query'>[]=[
 {id:'krugerrand',name:{de:'Krügerrand Goldmünze',en:'Krugerrand gold coin',fr:'Pièce d’or Krugerrand'},detail:{de:'Der südafrikanische Krügerrand unterscheidet sich durch seine Gold-Kupfer-Legierung von hochfeinen Goldmünzen. Der ausgewiesene Feingoldanteil und das Bruttogewicht sind deshalb nicht identisch.',en:'The South African Krugerrand uses a gold-copper alloy rather than the high-fineness gold of some other bullion coins. Its declared fine-gold content and gross weight are therefore different measurements.',fr:'Le Krugerrand sud-africain utilise un alliage d’or et de cuivre, contrairement à certaines pièces en or de haute pureté. Sa teneur en or fin et son poids brut sont donc deux mesures distinctes.'},comparison:{de:'Vergleiche die 1-oz-Ausgabe mit einer 1-oz-Maple-Leaf-Münze anhand des Feingoldanteils. Ein höheres Bruttogewicht des Krügerrands bedeutet nicht automatisch mehr enthaltenes Gold. Teilstücke und Sammlerausgaben sind separat zu prüfen.',en:'Compare a 1 oz Krugerrand with a 1 oz Maple Leaf by fine-gold content. A higher gross weight does not automatically mean more gold. Fractional denominations and collector editions must be checked separately.',fr:'Comparez un Krugerrand d’une once avec une Maple Leaf d’une once selon leur teneur en or fin. Un poids brut plus élevé ne signifie pas automatiquement davantage d’or. Vérifiez séparément les fractions et éditions de collection.'},source:{name:'South African Mint — Krugerrand',url:'https://www.samint.co.za/wp-content/uploads/Krugerrand-Brochure.pdf'},legacy:'/de/goldmuenzen/kruegerrand'},
 {id:'maple-leaf',name:{de:'Maple Leaf Goldmünze',en:'Maple Leaf gold coin',fr:'Pièce d’or Maple Leaf'},detail:{de:'Die kanadische Maple Leaf stammt von der Royal Canadian Mint. Jahrgang und Stückelung entscheiden darüber, welche technischen Daten und Sicherheitsmerkmale für das angebotene Exemplar gelten.',en:'The Canadian Maple Leaf is issued by the Royal Canadian Mint. The year and denomination determine which specifications and security features apply to the offered coin.',fr:'La Maple Leaf canadienne est émise par la Monnaie royale canadienne. Le millésime et la fraction déterminent les caractéristiques techniques et les dispositifs de sécurité de l’exemplaire proposé.'},comparison:{de:'Prüfe bei aktuellen und älteren Maple Leafs die jeweilige Ausgabe statt Sicherheitsmerkmale heutiger Münzen vorauszusetzen. Vergleiche außerdem Bullionqualität und besondere Sammlerausführungen getrennt.',en:'Check the actual issue when comparing recent and older Maple Leafs rather than assuming all have today’s security features. Keep standard bullion and special collector finishes in separate comparisons.',fr:'Comparez les caractéristiques de chaque émission, sans attribuer aux anciens millésimes tous les dispositifs de sécurité actuels. Distinguez également les pièces d’investissement des finitions de collection.'},source:{name:'Royal Canadian Mint — Gold Maple Leaf',url:'https://www.mint.ca/en/shop/coins/2026/2026-gml-1-oz-9999-pure-gold-coin-bullion'},legacy:'/de/goldmuenzen/maple-leaf'},
 {id:'vienna-philharmonic',name:{de:'Wiener Philharmoniker Goldmünze',en:'Vienna Philharmonic gold coin',fr:'Pièce d’or Philharmonique de Vienne'},detail:{de:'Der Wiener Philharmoniker wird von der Münze Österreich herausgegeben. Bei der 1-oz-Ausgabe sind Nennwert und Metallwert unterschiedliche Größen: Der aufgedruckte Eurobetrag ist kein Kaufpreis.',en:'The Vienna Philharmonic is issued by the Austrian Mint. Face value and metal value are different: the euro denomination on a 1 oz coin is not its selling price.',fr:'La Philharmonique de Vienne est émise par la Monnaie autrichienne. Sa valeur faciale et sa valeur métallique diffèrent : le montant en euros inscrit sur la pièce d’une once n’est pas son prix de vente.'},comparison:{de:'Vergleiche die 1-oz-Version mit kleineren Stückelungen über den Preis je Gramm Feingold. Gleiche Musikmotive bedeuten nicht dieselbe Größe; Feingewicht und Nennwert müssen zur konkreten Ausgabe passen.',en:'Compare the 1 oz version with fractional sizes using cost per gram of fine gold. The same musical design does not imply the same size; fine weight and face value must match the exact denomination.',fr:'Comparez la version d’une once aux fractions selon le coût par gramme d’or fin. Un motif musical similaire ne garantit pas un poids identique : le poids fin et la valeur faciale doivent correspondre à la fraction choisie.'},source:{name:'Münze Österreich — Wiener Philharmoniker',url:'https://www.muenzeoesterreich.at/produkte/1-unze-gold-wiener-philharmoniker'},legacy:'/de/goldmuenzen/wiener-philharmoniker'},
 {id:'britannia',name:{de:'Britannia Goldmünze',en:'Britannia gold coin',fr:'Pièce d’or Britannia'},detail:{de:'Die Britannia wird von der britischen Royal Mint geprägt. Bei älteren und aktuellen Goldausgaben können sich Legierung und Sicherheitsmerkmale unterscheiden; der Jahrgang gehört deshalb zum Produktvergleich.',en:'The Britannia is struck by The Royal Mint in the United Kingdom. Alloy and security features can differ between older and recent gold issues, making the year part of the product comparison.',fr:'La Britannia est frappée par la Royal Mint britannique. L’alliage et les dispositifs de sécurité peuvent varier entre les émissions anciennes et récentes : le millésime fait donc partie de la comparaison.'},comparison:{de:'Vergleiche Britannia-Bullionmünzen mit gleicher Stückelung und Ausführung. Eine Polierte-Platte-Ausgabe kann andere Aufpreise als eine normale Anlagemünze haben. Produktfoto, Ausgabejahr und Beschreibung müssen zusammenpassen.',en:'Compare Britannia bullion coins of the same denomination and finish. A proof edition may carry a different premium from ordinary bullion. The product image, issue year and description should agree.',fr:'Comparez des Britannia de même fraction et de même finition. Une édition belle épreuve peut présenter une prime différente de celle d’une pièce d’investissement courante. Photo, millésime et description doivent concorder.'},source:{name:'The Royal Mint — Britannia',url:'https://www.royalmint.com/invest/bullion/bullion-coins/gold-coins/britannia/'}},
 {id:'american-eagle',name:{de:'American Eagle Goldmünze',en:'American Gold Eagle coin',fr:'Pièce d’or American Eagle'},detail:{de:'Der American Gold Eagle ist eine Goldmünzenserie der United States Mint. Er ist vom American Silver Eagle sowie vom American Gold Buffalo zu unterscheiden. Material, Stückelung und genaue Serie müssen ausdrücklich angegeben sein.',en:'The American Gold Eagle is a United States Mint gold coin series. It is distinct from the American Silver Eagle and American Gold Buffalo. Metal, denomination and exact series should all be stated explicitly.',fr:'L’American Gold Eagle est une série de pièces d’or de l’United States Mint. Elle se distingue de l’American Silver Eagle et de l’American Gold Buffalo. Le métal, la fraction et la série exacte doivent être clairement indiqués.'},comparison:{de:'Vergleiche Bullion-, Proof- und andere Sammlerausführungen nicht allein über den Namen Eagle. Prüfe den enthaltenen Feingoldanteil; Bruttogewicht, Nennwert und Feingoldgewicht bezeichnen unterschiedliche Eigenschaften.',en:'Do not compare bullion, proof and other collector editions solely by the Eagle name. Check fine-gold content: gross weight, face value and fine-gold weight describe different properties.',fr:'Ne comparez pas les versions d’investissement, belle épreuve et autres éditions de collection sur le seul nom Eagle. Vérifiez la teneur en or fin : poids brut, valeur faciale et poids d’or fin désignent des propriétés différentes.'},source:{name:'United States Mint — American Eagle',url:'https://www.usmint.gov/coins/coin-medal-programs/american-eagle'}}
];
products.push(...coins.map(p=>({...p,kind:'coin' as const,grams:31.1035,size:'1 oz',query:{de:p.name.de,en:p.name.en,fr:p.name.fr}})));
export function productPath(product:Product,region:Region){
 if(region==='de'&&product.legacy)return product.legacy;
 const category=region==='de'?(product.kind==='bar'?'goldbarren':'goldmuenzen'):region==='fr'?(product.kind==='bar'?'lingots-or':'pieces-or'):(product.kind==='bar'?'gold-bars':'gold-coins');
 return `${region==='global'?'':`/${region}`}/${category}/${product.id.replace(/^bar-/,'')}`;
}
export function findProductPage(path:string){for(const region of regions){const product=products.find(p=>productPath(p,region)===path);if(product)return{product,region};}return undefined;}
export function productAlternates(product:Product){return Object.fromEntries([...regions.map(r=>[markets[r].hreflang,`${origin}${productPath(product,r)}`]),['x-default',`${origin}${productPath(product,'global')}`]]);}
export function hubAlternates(){return Object.fromEntries([...regions.map(r=>[markets[r].hreflang,`${origin}${markets[r].hub}`]),['x-default',`${origin}/products`]]);}
export const productPages=regions.flatMap(region=>products.map(product=>({region,product,path:productPath(product,region)})));
export const ui={
 de:{catalogue:'Goldprodukte vergleichen',bars:'Goldbarren nach Gewicht',coins:'Goldmünzen nach Serie',quick:'Kurzantwort',facts:'Produktdaten einordnen',compare:'Größen und Ausführungen vergleichen',cost:'Preis pro Gramm richtig berechnen',region:'Kauf und Lieferung in Deutschland',sources:'Offizielle Produktquellen',related:'Weitere Produkte vergleichen',faq:'Häufige Fragen',languages:'Land und Sprache',reviewed:'Redaktionell überarbeitet',weight:'Gewicht / Referenzgröße',type:'Produkttyp',purity:'Feingehalt',purityValue:'Im konkreten Herstellerangebot prüfen',bar:'Goldbarren',coin:'Goldmünze · Referenz: 1-oz-Ausgabe',note:'Diese Seite beschreibt ein Produktformat. Hersteller, Jahrgang, Feinheit und Verfügbarkeit hängen vom konkreten Angebot ab.',offers:'Angebote und Bezugsquellen',legal:'Impressum',privacy:'Datenschutz',disclosure:'Gold Finder verkauft kein Gold. Amazon-Links mit Partnerkennung sind Werbung; bei einem qualifizierten Kauf können wir eine Provision erhalten.',home:'Startseite',all:'Alle Produkte',method:'Vergleichsmethode',guideIntro:'Vergleiche Goldbarren nach Gewicht und Goldmünzen nach Serie. Jede Produktseite erklärt die Unterschiede, zeigt Vergleichsrechnungen und nennt offizielle Quellen.',priceFaq:'Warum gibt es keinen festen Preis?',priceAnswer:'Der Verkaufspreis hängt von Goldkurs, Hersteller, Verkäufer, Aufgeld und Lieferung ab. Ein Beispielbetrag ist kein aktuelles Angebot. Verbindlich ist der Preis des Anbieters beim Kauf.',authFaq:'Wie prüfe ich das konkrete Produkt?',authAnswer:'Gleiche Gewicht, Feinheit, Hersteller oder Prägestätte, Jahrgang und Verpackung mit der offiziellen Quelle ab. Ein Bild oder Zertifikat allein ersetzt keine Prüfung durch einen vertrauenswürdigen Anbieter.',info:'Produktinformation, keine individuelle Anlageberatung.'},
 en:{catalogue:'Compare gold products',bars:'Gold bars by weight',coins:'Gold coins by series',quick:'Quick answer',facts:'Understand the product specifications',compare:'Compare sizes and editions',cost:'Calculate the price per gram',region:'Buying and delivery',sources:'Official product sources',related:'Compare other products',faq:'Frequently asked questions',languages:'Country and language',reviewed:'Editorial update',weight:'Weight / reference size',type:'Product type',purity:'Fineness',purityValue:'Verify in the specific manufacturer listing',bar:'Gold bar',coin:'Gold coin · reference: 1 oz edition',note:'This page describes a product format. Manufacturer, issue year, fineness and availability depend on the specific listing.',offers:'Offers and buying sources',legal:'Legal notice',privacy:'Privacy',disclosure:'Gold Finder does not sell gold. Amazon links with an associate tag are advertising; we may earn a commission from qualifying purchases.',home:'Home',all:'All products',method:'Comparison method',guideIntro:'Compare gold bars by weight and gold coins by series. Each product page explains differences, provides comparison calculations and links to official sources.',priceFaq:'Why is there no fixed price?',priceAnswer:'The selling price depends on the gold market, refiner, seller, premium and delivery. An example amount is not a current offer. The seller’s price at purchase is authoritative.',authFaq:'How do I check a specific product?',authAnswer:'Match weight, fineness, refiner or mint, issue year and packaging to the official source. A photo or certificate alone does not replace verification by a trustworthy supplier.',info:'Product information, not personal investment advice.'},
 fr:{catalogue:'Comparer les produits en or',bars:'Lingots d’or par poids',coins:'Pièces d’or par série',quick:'Réponse rapide',facts:'Comprendre les caractéristiques du produit',compare:'Comparer les formats et les éditions',cost:'Calculer le prix par gramme',region:'Achat et livraison en France',sources:'Sources officielles du produit',related:'Comparer d’autres produits',faq:'Questions fréquentes',languages:'Pays et langue',reviewed:'Mise à jour éditoriale',weight:'Poids / format de référence',type:'Type de produit',purity:'Titre',purityValue:'À vérifier dans la fiche du fabricant concerné',bar:'Lingot d’or',coin:'Pièce d’or · référence : édition d’une once',note:'Cette page décrit un format de produit. Le fabricant, le millésime, le titre et la disponibilité dépendent de l’offre précise.',offers:'Offres et points d’achat',legal:'Mentions légales',privacy:'Confidentialité',disclosure:'Gold Finder ne vend pas d’or. Les liens Amazon comportant un identifiant partenaire sont publicitaires ; un achat éligible peut nous rapporter une commission.',home:'Accueil',all:'Tous les produits',method:'Méthode de comparaison',guideIntro:'Comparez les lingots par poids et les pièces par série. Chaque fiche explique les différences, propose des calculs comparatifs et renvoie aux sources officielles.',priceFaq:'Pourquoi n’y a-t-il pas de prix fixe ?',priceAnswer:'Le prix de vente dépend du cours de l’or, de l’affineur, du vendeur, de la prime et de la livraison. Un montant donné en exemple n’est pas une offre actuelle. Le prix du vendeur au moment de l’achat fait foi.',authFaq:'Comment vérifier un produit précis ?',authAnswer:'Vérifiez le poids, le titre, le fabricant ou l’atelier monétaire, le millésime et le conditionnement à partir de la source officielle. Une photo ou un certificat ne remplace pas la vérification par un fournisseur fiable.',info:'Information sur les produits, sans conseil personnalisé en investissement.'},
};
export const regionalCopy:Record<Region,{intro:string;delivery:string;unit:string;offerNote:string}>={
 global:{intro:'Use this international English guide to compare the underlying product before choosing a country. A worldwide reference page does not imply worldwide shipping or the same offer in every market.',delivery:'Choose the destination country before comparing sellers. Keep the quote currency consistent, check insured cross-border delivery and include any conversion, import or payment costs confirmed by the seller.',unit:'Use troy ounces for bullion quotes and grams for metric bar comparisons. A price quoted in another currency must be converted at the same point in time before comparing premiums.',offerNote:'Select a country below for the corresponding buying context. Offers, delivery and marketplace access depend on that destination.'},
 de:{intro:'Für Käufer in Deutschland steht der Gesamtpreis in Euro im Mittelpunkt. Vergleiche Angebote mit Lieferung an dieselbe deutsche Postleitzahl, damit Versandkosten und mögliche Abholung auf derselben Grundlage stehen.',delivery:'Prüfe, ob Wertversand bis zur Übergabe versichert ist und wer das Paket annehmen darf. Bei einem Anbieter außerhalb Deutschlands sind Liefergebiet, Rücksendeadresse und gegebenenfalls zusätzliche Einfuhrkosten vorab zu klären.',unit:'Metrische Gewichte lassen sich direkt in Euro je Gramm vergleichen. Bei Unzenangeboten zuerst die Feinunze in Gramm umrechnen; bei Münzen den Feingoldanteil statt des Bruttogewichts verwenden.',offerNote:'Angebote stammen, soweit verfügbar, aus Amazon.de. Preis, Verkäufer und Lieferbarkeit müssen auf der jeweiligen Angebotsseite bestätigt werden.'},
 fr:{intro:'Pour un achat en France, comparez le coût total en euros pour la même adresse de livraison. Les termes lingotin et lingot décrivent des formats, mais ne remplacent pas les indications de poids et de titre.',delivery:'Demandez les conditions de livraison assurée, de remise au destinataire et de retour. Pour un vendeur situé hors de France, vérifiez le pays d’expédition, les frais éventuels et les conditions de rachat avant de commander.',unit:'Utilisez le prix en euros par gramme d’or fin pour rapprocher les formats métriques et les pièces d’une once. Le mot once doit désigner l’once troy ; le poids brut d’une pièce peut différer de son poids d’or fin.',offerNote:'Le catalogue Amazon.fr en direct n’est pas encore connecté. Vous pouvez consulter la source officielle ou effectuer une recherche sur Amazon.fr ; aucun prix ni stock local n’est affirmé ici.'},
 us:{intro:'For a United States purchase, compare the total in US dollars delivered to the same ZIP code. A gram-denominated bar and an ounce-denominated coin should be compared using fine-gold content, not their ticket prices.',delivery:'Confirm delivery to your state, insured shipping, signature requirements and the seller’s payment conditions. Check any sales tax shown for your delivery address and avoid assuming that a price seen for another state is your checkout total.',unit:'US bullion quotes commonly use troy ounces. Divide the dollar quote per troy ounce by 31.1035 to compare it with a gram-based reference, using quotes from the same time. This conversion does not include the seller’s premium.',offerNote:'Where available, listings use Amazon.com. Marketplace selection does not guarantee delivery to every US address. Confirm the actual seller and checkout terms.'},
 uk:{intro:'For a United Kingdom purchase, compare the delivered total in pounds sterling. A euro or US dollar quote is not directly comparable until conversion, delivery and any import costs are included.',delivery:'Confirm UK delivery coverage and insured handover. A seller dispatching from outside the UK can have different shipping and import terms. Keep tax questions separate from a product’s name and check current HMRC guidance for the exact item and your circumstances.',unit:'A troy ounce and a metric gram are both used in UK bullion offers. Compare the same fine-gold amount in pounds; a coin’s face value is not the amount you pay or its metal value.',offerNote:'Where available, listings use Amazon.co.uk. Check the specific delivery address and final sterling amount on the seller’s page.'},
};
