import type { Metadata } from 'next';
import LegalPage from '../../components/LegalPage';
export const metadata: Metadata = {title:'Privacy Policy / Datenschutz — Gold Finder',alternates:{canonical:'/datenschutz'}};
export default function Datenschutz(){return <LegalPage title="Privacy Policy / Datenschutz">
<p>This notice explains the processing of personal data when you visit gold-finder.com or contact its operator.</p>
<h2>1. Controller and contact</h2><address>Pascal Weyers<br/>Birkenwaldstr. 46<br/>63179 Obertshausen, Germany<br/>Email: <a href="mailto:info@noonoo.de">info@noonoo.de</a></address>
<h2>2. Hosting and technical access data</h2><p>The website is hosted by Vercel Inc., USA. When a page or file is requested, technical information such as IP address, requested URL, date and time, browser information, referring page where transmitted, and response or error information may be processed to deliver and protect the service.</p><p>Our legal basis is Article 6(1)(f) GDPR: our legitimate interest in providing a reliable and secure website. Vercel acts as a processor for customer data under its <a href="https://vercel.com/legal/dpa">Data Processing Addendum</a> and may process certain service-generated data under its own responsibility. See the <a href="https://vercel.com/legal/privacy-notice">Vercel Privacy Notice</a>.</p><p>Hosting data is kept only for the period needed for delivery, security, troubleshooting and applicable legal requirements. Retention depends on the type of log and the hosting service; we do not maintain a separate visitor database.</p>
<h2>3. International processing</h2><p>Vercel uses international infrastructure, so processing may take place outside the EU/EEA, including in the United States. Its data-processing terms provide transfer safeguards, including standard contractual clauses where applicable. Details and information on subprocessors are available in the linked Vercel terms.</p>
<h2>4. Search, filters and comparisons</h2><p>Search and filter selections are processed in your browser and reflected in URL parameters so a filtered view can be shared. Comparison selections remain in page memory. The application does not store these choices in cookies or local storage. If you reload or share a filtered URL, its parameters are transmitted with the request and may appear in technical logs or browser history. Please do not enter personal or sensitive information into the product search.</p>
<h2>5. Cookies, analytics, fonts and images</h2><p>The current website does not include advertising pixels, analytics scripts, newsletter forms or user accounts. Its application code does not set cookies or use browser storage for tracking. Fonts and website images are served from this website through the hosting service; visiting a page does not require loading Google Fonts from Google servers.</p>
<h2>6. Amazon affiliate links and other websites</h2><p>Amazon links contain the affiliate identifier for the selected marketplace: Onlinestarkei-21 for Germany, goldfindercom-20 for the United States, or goldfindercom-21 for the United Kingdom. Clicking a link opens the corresponding product detail page on that local Amazon marketplace. Amazon then receives the connection information needed to load its site and may use cookies or other technologies under its own policies and your settings. We do not embed Amazon tracking scripts on this website or receive your payment details through these links.</p><p>The same principle applies to links to dealers, mints and other external sources: the destination processes your data when you visit it. Please consult its privacy notice. For Amazon, see its <a href="https://www.amazon.de/gp/help/customer/display.html?nodeId=GX7NJQ4ZB8MHFRNJ">Privacy Notice</a>. Our legitimate interest under Article 6(1)(f) GDPR is to provide relevant product links and finance our information service through referrals.</p>
<h2>7. Contact by email</h2><p>If you email us, we process your address, message and any voluntarily supplied details to answer your request. The legal basis is Article 6(1)(b) GDPR for contractual or pre-contractual enquiries, otherwise Article 6(1)(f) GDPR for responding to correspondence. Email providers process messages for transmission and delivery. Messages are deleted when no longer needed, unless retention obligations or the defence of legal claims require continued storage.</p>
<h2>8. Your rights</h2><p>Subject to the applicable conditions, you may request access, correction, erasure, restriction and data portability. You may object to processing based on legitimate interests for reasons relating to your situation. Where processing relies on consent, you may withdraw it prospectively. Contact the controller above to exercise your rights.</p><p>You may complain to a supervisory authority, including the <a href="https://datenschutz.hessen.de/">Hessian Commissioner for Data Protection and Freedom of Information</a> or the authority where you live or work.</p>
<h2>9. Providing data and updates</h2><p>Technical connection data is necessary to deliver the website. Contacting us is voluntary. We do not use your data for automated decisions producing legal or similarly significant effects. We update this notice when the website or its processing changes.</p>
<p>Operator details: <a href="/impressum">Legal Notice / Impressum</a>.</p>
</LegalPage>}
