'use client';
import {useEffect,useMemo,useState} from 'react';
import {Search,SlidersHorizontal,Scale,ShieldCheck,Globe2,ArrowUpRight,Check,Menu,X,ChevronDown,Coins,Box,BookOpen} from 'lucide-react';

type Product={id:string;name:string;type:'Bar'|'Coin';weight:string;grams:number;purity:string;maker:string;series:string;dealer:string;regions:string[];url:string;note:string};
const products:Product[]=[
 {id:'britannia',name:'Britannia 1 oz Gold Bullion Coin',type:'Coin',weight:'1 troy oz',grams:31.1035,purity:'999.9',maker:'The Royal Mint',series:'Britannia',dealer:'The Royal Mint',regions:['UK','Europe','International'],url:'https://www.royalmint.com/invest/bullion/uk-coins/britannia/',note:'Official product page'},
 {id:'maple',name:'Maple Leaf 1 oz Gold Coin',type:'Coin',weight:'1 troy oz',grams:31.1035,purity:'999.9',maker:'Royal Canadian Mint',series:'Maple Leaf',dealer:'APMEX',regions:['US','International'],url:'https://www.apmex.com/category/10000/gold',note:'Dealer category page'},
 {id:'krugerrand',name:'Krugerrand 1 oz Gold Coin',type:'Coin',weight:'1 troy oz',grams:33.93,purity:'916.7',maker:'South African Mint',series:'Krugerrand',dealer:'BullionByPost',regions:['UK','Europe'],url:'https://www.bullionbypost.co.uk/gold-coins/krugerrand-gold-coins/',note:'Dealer product range'},
 {id:'rm-1oz',name:'1 oz Minted Gold Bar',type:'Bar',weight:'1 troy oz',grams:31.1035,purity:'999.9',maker:'The Royal Mint',series:'Minted bar',dealer:'The Royal Mint',regions:['UK','Europe','International'],url:'https://www.royalmint.com/invest/bullion-by-weight/one-ounce-gold-bullion-bars/',note:'Official product page'},
 {id:'pamp-10g',name:'PAMP Suisse 10 g Gold Bar',type:'Bar',weight:'10 g',grams:10,purity:'999.9',maker:'PAMP Suisse',series:'Fortuna',dealer:'APMEX',regions:['US','International'],url:'https://www.apmex.com/category/19320/pamp-suisse-gold-bars',note:'Dealer product range'},
 {id:'valcambi-100g',name:'Valcambi 100 g Gold Bar',type:'Bar',weight:'100 g',grams:100,purity:'999.9',maker:'Valcambi',series:'Cast bar',dealer:'BullionByPost',regions:['UK','Europe'],url:'https://www.bullionbypost.co.uk/gold-bars/100-gram-gold-bar/',note:'Dealer product range'}
];
const sources=[
 ['The Royal Mint','https://www.royalmint.com/invest/bullion/','Product formats, weights and purchase flow'],
 ['GOLD.DE','https://www.gold.de/kaufen/','Comparison structure and dealer transparency'],
 ['APMEX','https://www.apmex.com/category/10000/gold','International product taxonomy'],
 ['BullionByPost','https://www.bullionbypost.co.uk/gold/','Weight-led browsing and product ranges']
];

export default function GoldFinder(){
 const [query,setQuery]=useState(''); const [type,setType]=useState('All'); const [region,setRegion]=useState('International'); const [sort,setSort]=useState('name'); const [compare,setCompare]=useState<string[]>([]); const [mobile,setMobile]=useState(false);
 useEffect(()=>{const p=new URLSearchParams(location.search);setQuery(p.get('q')||'');setType(p.get('type')||'All');setRegion(p.get('region')||'International')},[]);
 useEffect(()=>{const p=new URLSearchParams();if(query)p.set('q',query);if(type!=='All')p.set('type',type);if(region!=='International')p.set('region',region);history.replaceState(null,'',`${location.pathname}${p.size?'?'+p:''}`)},[query,type,region]);
 const visible=useMemo(()=>products.filter(p=>(type==='All'||p.type===type)&&p.regions.includes(region)&&(p.name+p.maker+p.series+p.dealer).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='weight'?a.grams-b.grams:a.name.localeCompare(b.name)),[query,type,region,sort]);
 const toggle=(id:string)=>setCompare(c=>c.includes(id)?c.filter(x=>x!==id):c.length<4?[...c,id]:c);
 return <main>
  <header><a className="brand" href="#top"><span>AU</span> GOLD FINDER</a><nav className={mobile?'open':''}><a href="#finder">Finder</a><a href="#guide">Buying guide</a><a href="#dealers">Dealers</a><a href="#about">About</a></nav><button className="menu" aria-label="Menu" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></header>
  <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">Independent bullion discovery</p><h1>Find your gold.<br/><em>Invest with clarity.</em></h1><p>Explore recognised bars and coins, understand the trade-offs, then continue to a verified dealer page.</p><a className="button light" href="#finder">Start exploring <ArrowUpRight size={17}/></a></div></section>
  <section className="finder" id="finder"><div className="finder-intro"><p className="eyebrow">Gold finder</p><h2>A clearer way to explore physical gold.</h2><p>Use the essentials first. Every result links to a source page; live prices will appear only after an authorised feed is connected.</p></div>
   <div className="controls"><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search coin, bar, mint or dealer"/></label><Select label="Format" icon={<SlidersHorizontal/>} value={type} set={setType} options={['All','Bar','Coin']}/><Select label="Delivery region" icon={<Globe2/>} value={region} set={setRegion} options={['International','Europe','UK','US']}/><Select label="Sort" icon={<ChevronDown/>} value={sort} set={setSort} options={['name','weight']}/></div>
   <div className="result-head"><span>{visible.length} recognised products</span><button onClick={()=>{setQuery('');setType('All');setRegion('International')}}>Reset filters</button></div>
   <div className="grid">{visible.map((p,i)=><article className="card" key={p.id}><div className={`metal ${p.type.toLowerCase()}`}>{p.type==='Coin'?<Coins/>:<Box/>}<span>{String(i+1).padStart(2,'0')}</span></div><div className="card-body"><div className="tag">{p.type} · {p.weight}</div><h3>{p.name}</h3><dl><div><dt>Fine weight</dt><dd>{p.grams===33.93?'1 oz fine gold':`${p.grams} g`}</dd></div><div><dt>Fineness</dt><dd>{p.purity}</dd></div><div><dt>Maker / mint</dt><dd>{p.maker}</dd></div><div><dt>Source</dt><dd>{p.dealer}</dd></div></dl><p className="no-price">Price unavailable · feed connection pending</p><div className="actions"><a href={p.url} target="_blank" rel="nofollow sponsored noopener">View source <ArrowUpRight size={15}/></a><button className={compare.includes(p.id)?'selected':''} onClick={()=>toggle(p.id)}>{compare.includes(p.id)?<Check size={14}/>:<Scale size={14}/>} Compare</button></div></div></article>)}</div>
   {!visible.length&&<div className="empty"><Search/><h3>No matches yet</h3><p>Try another region or remove a filter.</p></div>}
  </section>
  {compare.length>0&&<aside className="compare"><div><Scale/><strong>Compare selection</strong><span>{compare.length}/4 products</span></div><div>{compare.map(id=><button key={id} onClick={()=>toggle(id)}>{products.find(p=>p.id===id)?.name}<X size={13}/></button>)}</div><a href="#comparison">Review comparison</a></aside>}
  <section className="comparison" id="comparison"><p className="eyebrow">Side by side</p><h2>Your selected gold</h2>{compare.length?<div className="compare-grid">{compare.map(id=>{const p=products.find(x=>x.id===id)!;return <article key={id}><h3>{p.name}</h3><p>{p.type} · {p.weight}</p><p>{p.purity} fine</p><p>{p.maker}</p><a href={p.url} target="_blank" rel="nofollow sponsored noopener">Open source <ArrowUpRight size={14}/></a></article>})}</div>:<p className="muted">Choose up to four products in the finder to compare their core specifications.</p>}</section>
  <section className="guide" id="guide"><div><p className="eyebrow">Buying guide</p><h2>Know what you are comparing.</h2><p>Physical gold is simple in principle, but size, premium, delivery and storage all shape the final decision.</p><a href="https://www.royalmint.com/invest/discover/invest-in-gold/an-introduction-to-investing-in-precious-metals-what-are-my-options/" target="_blank">Read the source guide <ArrowUpRight size={15}/></a></div><div className="guide-list"><Guide n="01" title="Bars or coins?" text="Bars often concentrate value efficiently. Coins may offer recognisable designs and more flexible resale sizes."/><Guide n="02" title="Weight and fineness" text="One troy ounce equals 31.1035 grams. Fineness describes the proportion of pure gold in the item."/><Guide n="03" title="Premium and total cost" text="Compare fabrication premiums, insured delivery, payment fees and any applicable local taxes—not only the metal value."/><Guide n="04" title="Storage and exit" text="Plan secure storage, insurance and a resale route before buying. Terms differ by dealer and country."/></div></section>
  <section className="trust" id="dealers"><ShieldCheck/><div><p className="eyebrow">Source-led by design</p><h2>Clarity before clicks.</h2></div><p>We do not invent ratings, prices or partnerships. Current links point to public dealer or mint pages. Future affiliate placements will be labelled, and sponsored status will never determine the displayed product facts.</p></section>
  <section className="sources"><p className="eyebrow">Research references</p><h2>What shaped this first release.</h2><div>{sources.map(s=><a key={s[0]} href={s[1]} target="_blank"><strong>{s[0]}</strong><span>{s[2]}</span><ArrowUpRight/></a>)}</div></section>
  <section className="about" id="about"><div><p className="eyebrow">About Gold Finder</p><h2>Built for calm, informed exploration.</h2></div><div><p>Gold Finder is an independent discovery interface for internationally recognised physical bullion products. It is not a dealer, broker or financial adviser.</p><p id="disclosure"><strong>Affiliate disclosure.</strong> Some outbound links may become affiliate links. If that happens, Gold Finder may earn a commission without changing your purchase price. Such links will be clearly marked.</p><p id="privacy"><strong>Privacy.</strong> This demonstration stores filter state in the page URL only. No account, analytics or contact form is enabled. Operator and jurisdiction details must be supplied before a production legal notice can be completed.</p></div></section>
  <section className="faq" id="faq"><p className="eyebrow">FAQ</p><h2>Answers without the sales pitch.</h2><details><summary>Does Gold Finder sell gold?</summary><p>No. It helps visitors explore products and continue to external dealer or mint pages.</p></details><details><summary>Are the prices live?</summary><p>No live price feed is connected in this release, so the interface does not display price claims.</p></details><details><summary>Is this financial advice?</summary><p>No. Gold can rise or fall in value. Consider your circumstances, costs, taxes and independent professional advice.</p></details></section>
  <footer><a className="brand" href="#top"><span>AU</span> GOLD FINDER</a><p>Independent discovery for physical gold.</p><div><a href="#disclosure">Affiliate disclosure</a><a href="#privacy">Privacy</a><a href="#faq">FAQ</a></div><small>© {new Date().getFullYear()} Gold Finder. Information only; no investment advice.</small></footer>
 </main>
}
function Select({label,icon,value,set,options}:{label:string;icon:React.ReactNode;value:string;set:(v:string)=>void;options:string[]}){return <label className="select">{icon}<span>{label}<select value={value} onChange={e=>set(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></span></label>}
function Guide({n,title,text}:{n:string;title:string;text:string}){return <article><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div><BookOpen/></article>}
