'use client';
import {useEffect,useMemo,useState} from 'react';
import Image from 'next/image';
import {Search,Scale,ShieldCheck,ArrowUpRight,Check,Menu,X,ChevronDown,BookOpen} from 'lucide-react';
import type {AmazonProduct,ProductResponse} from '@/lib/types';
import BrandLogo from './BrandLogo';

const sources=[
 ['The Royal Mint','https://www.royalmint.com/invest/bullion/','Product formats, weights and purchase flow'],
 ['GOLD.DE','https://www.gold.de/kaufen/','Comparison structure and dealer transparency'],
 ['APMEX','https://www.apmex.com/category/10000/gold','International product taxonomy'],
 ['BullionByPost','https://www.bullionbypost.co.uk/gold/','Weight-led browsing and product ranges']
];
export default function GoldFinder(){
 const [marketInfo,setMarketInfo]=useState({name:'Germany',amazon:'Amazon.de',currency:'Euro'}); const [products,setProducts]=useState<AmazonProduct[]>([]); const [live,setLive]=useState(false); const [loading,setLoading]=useState(true); const [message,setMessage]=useState('Loading current marketplace products…');
 const [query,setQuery]=useState(''); const [type,setType]=useState('All'); const [weight,setWeight]=useState('All'); const [budget,setBudget]=useState('All'); const [brand,setBrand]=useState('All brands'); const [sort,setSort]=useState('name'); const [compare,setCompare]=useState<string[]>([]); const [mobile,setMobile]=useState(false);
 useEffect(()=>{const p=new URLSearchParams(location.search);setQuery(p.get('q')||'');setType(p.get('type')||'All');setWeight(p.get('weight')||'All');setBudget(p.get('budget')||'All');setBrand(p.get('brand')||'All brands')},[]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setProducts([]);setCompare([]);fetch('/api/products',{signal:controller.signal}).then(r=>r.json()).then((data:ProductResponse)=>{setProducts(data.products);setMarketInfo({name:data.marketplaceName,amazon:data.amazonDomain.replace('www.','').replace('amazon','Amazon'),currency:data.currency==='EUR'?'Euro':data.currency==='USD'?'US dollar':'British pound'});setLive(data.live);setMessage(data.message||'');setLoading(false)}).catch(e=>{if(e.name!=='AbortError'){setProducts([]);setLive(false);setMessage('Amazon live products are temporarily unavailable. No cached prices are being shown.');setLoading(false)}});return()=>controller.abort()},[]);
 useEffect(()=>{const p=new URLSearchParams();if(query)p.set('q',query);if(type!=='All')p.set('type',type);if(weight!=='All')p.set('weight',weight);if(budget!=='All')p.set('budget',budget);if(brand!=='All brands')p.set('brand',brand);history.replaceState(null,'',`${location.pathname}${p.size?'?'+p:''}`)},[query,type,weight,budget,brand]);
 const brands=useMemo(()=>['All brands',...Array.from(new Set(products.map(p=>p.brand).filter(Boolean))).sort((a,b)=>a.localeCompare(b))],[products]);
 const visible=useMemo(()=>products.filter(p=>{
  const text=`${p.title} ${p.brand} ${p.model} ${p.features.join(' ')}`;
  const formatMatch=type==='All'||(type==='Bars'?/bar|barren|combibar/i.test(text):/coin|münze|krugerrand|krügerrand|britannia|maple leaf|philharmoniker|eagle|kangaroo|känguru/i.test(text));
  const price=p.price?.amount,priceMatch=budget==='All'||(budget==='Under 250'?price!==undefined&&price<250:budget==='250–1,000'?price!==undefined&&price>=250&&price<1000:price!==undefined&&price>=1000);
  return formatMatch&&matchesWeight(text,weight)&&priceMatch&&(brand==='All brands'||p.brand===brand)&&text.toLowerCase().includes(query.toLowerCase());
 }).sort((a,b)=>sort==='price'?(a.price?.amount??Infinity)-(b.price?.amount??Infinity):a.title.localeCompare(b.title)),[products,query,type,weight,budget,brand,sort]);
 const toggle=(id:string)=>setCompare(c=>c.includes(id)?c.filter(x=>x!==id):c.length<4?[...c,id]:c);
 const reset=()=>{setQuery('');setType('All');setWeight('All');setBudget('All');setBrand('All brands')};
 return <main>
  <header><a className="brand" href="#top"><BrandLogo/></a><nav className={mobile?'open':''}><a href="#finder">Finder</a><a href="#guide">Buying guide</a><a href="#dealers">Dealers</a><a href="#about">About</a></nav><button className="menu" aria-label="Menu" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></header>
  <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">Independent bullion discovery</p><h1>Find your gold.<br/><em>Invest with clarity.</em></h1><p>Explore recognised bars and coins, understand the trade-offs, then continue to a verified dealer page.</p><a className="button light" href="#finder">Start exploring <ArrowUpRight size={17}/></a></div></section>
  <section className="finder" id="finder"><div className="finder-intro"><p className="eyebrow">Gold finder</p><h2>A clearer way to explore physical gold.</h2><p>Explore locally available gold products with product language, currency, availability and partner links selected automatically for the visitor’s country.</p></div>
   <div className="filter-panel"><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search product, brand or feature"/></label><div className="quick-filters"><FilterChips label="Format" value={type} set={setType} options={['All','Bars','Coins']}/><FilterChips label="Weight" value={weight} set={setWeight} options={['All','Up to 1 g','2–5 g','10–20 g','1 oz +']}/><FilterChips label={`Price · ${marketInfo.currency}`} value={budget} set={setBudget} options={['All','Under 250','250–1,000','1,000 +']}/></div><div className="filter-selects"><Select label="Brand" icon={<ChevronDown/>} value={brand} set={setBrand} options={brands}/><Select label="Sort by" icon={<ChevronDown/>} value={sort} set={setSort} options={['name','price']}/></div></div>
   <div className="result-head"><span>{loading?'Loading local catalogue…':live?`${visible.length} of ${products.length} currently available models on ${marketInfo.amazon}`:'Live selection unavailable'}</span><button onClick={reset}>Reset all filters</button></div>
   {!loading&&!live&&<div className="api-status"><strong>Live Amazon data unavailable</strong><p>{message}</p></div>}
   <div className="grid">{visible.map((p,i)=><article className="card" key={p.asin}><div className="product-image"><Image src={p.image} alt={p.title} fill sizes="(max-width: 590px) 90vw, (max-width: 900px) 45vw, 30vw"/><span>{String(i+1).padStart(2,'0')}</span></div><div className="card-body"><div className="tag">{marketInfo.amazon} · ASIN {p.asin}</div><h3 title={p.title}>{p.title}</h3><dl><div><dt>Brand</dt><dd>{p.brand}</dd></div><div><dt>Model</dt><dd>{p.model}</dd></div><div><dt>Availability</dt><dd>{p.availability}</dd></div><div><dt>Parent ASIN</dt><dd>{p.parentAsin}</dd></div></dl><ul className="features" aria-label="Product features">{p.features.slice(0,3).map(feature=><li key={feature} title={feature}>{feature}</li>)}</ul><p className={p.price?'live-price':'no-price'}>{p.price?.display||`Current ${marketInfo.currency} price not supplied by Amazon`}</p><div className="actions"><a className="amazon" href={p.detailPageUrl} target="_blank" rel="nofollow sponsored noopener">Advertising link · View on Amazon <ArrowUpRight size={15}/></a><button className={compare.includes(p.asin)?'selected':''} onClick={()=>toggle(p.asin)}>{compare.includes(p.asin)?<Check size={14}/>:<Scale size={14}/>} Compare</button></div></div></article>)}</div>
   <p className="amazon-note">Prices and availability can change at any time. The product detail page and offer shown by {marketInfo.amazon} at the time of purchase are authoritative. All Amazon links are advertising links.</p>
   {!loading&&live&&!visible.length&&<div className="empty"><Search/><h3>No matches yet</h3><p>Try another search or reset one of the filters above.</p></div>}
  </section>
  {compare.length>0&&<aside className="compare"><div><Scale/><strong>Compare selection</strong><span>{compare.length}/4 products</span></div><div>{compare.map(id=><button key={id} onClick={()=>toggle(id)}>{products.find(p=>p.asin===id)?.title}<X size={13}/></button>)}</div><a href="#comparison">Review comparison</a></aside>}
  <section className="comparison" id="comparison"><p className="eyebrow">Side by side</p><h2>Your selected gold</h2>{compare.length?<div className="compare-grid">{compare.map(id=>{const p=products.find(x=>x.asin===id)!;return p&&<article key={id}><h3>{p.title}</h3><p>{p.brand} · {p.model}</p><p>{p.price?.display||'No current Euro price'}</p><p>ASIN {p.asin}</p><a href={p.detailPageUrl} target="_blank" rel="nofollow sponsored noopener">Advertising link · Amazon <ArrowUpRight size={14}/></a></article>})}</div>:<p className="muted">Choose up to four products in the finder to compare their current Amazon data.</p>}</section>
  <section className="seo-hubs"><p className="eyebrow">Gold knowledge</p><h2>Research before you choose.</h2><div><a href="/de/goldbarren-kaufen"><span>Deutschland</span><strong>Goldbarren kaufen und vergleichen</strong><ArrowUpRight/></a><a href="/de/goldmuenzen-kaufen"><span>Deutschland</span><strong>Goldmünzen und Anlagemünzen</strong><ArrowUpRight/></a><a href="/guides/gold-bars-vs-coins"><span>Format guide</span><strong>Gold bars vs coins</strong><ArrowUpRight/></a><a href="/guides/gold-bar-sizes"><span>Weight guide</span><strong>Gold bar sizes explained</strong><ArrowUpRight/></a><a href="/coins/krugerrand-vs-maple-leaf-vs-britannia"><span>Coin comparison</span><strong>Krugerrand, Maple Leaf or Britannia?</strong><ArrowUpRight/></a><a href="/how-gold-finder-works"><span>Transparent methodology</span><strong>How Gold Finder validates products</strong><ArrowUpRight/></a><a href="/us/buy-gold"><span>United States</span><strong>Buying physical gold in the USA</strong><ArrowUpRight/></a><a href="/uk/buy-gold"><span>United Kingdom</span><strong>Buying physical gold in the UK</strong><ArrowUpRight/></a><a href="/de/gold-kaufen"><span>Deutschland</span><strong>Anlagegold verständlich vergleichen</strong><ArrowUpRight/></a></div></section>
  <section className="guide" id="guide"><div><p className="eyebrow">Buying guide</p><h2>Know what you are comparing.</h2><p>Physical gold is simple in principle, but size, premium, delivery and storage all shape the final decision.</p><a href="https://www.royalmint.com/invest/discover/invest-in-gold/an-introduction-to-investing-in-precious-metals-what-are-my-options/" target="_blank">Read the source guide <ArrowUpRight size={15}/></a></div><div className="guide-list"><Guide n="01" title="Bars or coins?" text="Bars often concentrate value efficiently. Coins may offer recognisable designs and more flexible resale sizes."/><Guide n="02" title="Weight and fineness" text="One troy ounce equals 31.1035 grams. Fineness describes the proportion of pure gold in the item."/><Guide n="03" title="Premium and total cost" text="Compare fabrication premiums, insured delivery, payment fees and any applicable local taxes—not only the metal value."/><Guide n="04" title="Storage and exit" text="Plan secure storage, insurance and a resale route before buying. Terms differ by dealer and country."/></div></section>
  <section className="trust" id="dealers"><ShieldCheck/><div><p className="eyebrow">Source-led by design</p><h2>Clarity before clicks.</h2></div><p>We do not invent ratings, prices or partnerships. Dealer links point to public source pages. Amazon search links are clearly marked as affiliate links; sponsored status never determines the displayed product facts.</p></section>
  <section className="sources"><p className="eyebrow">Research references</p><h2>What shaped this first release.</h2><div>{sources.map(s=><a key={s[0]} href={s[1]} target="_blank"><strong>{s[0]}</strong><span>{s[2]}</span><ArrowUpRight/></a>)}</div></section>
  <section className="about" id="about"><div><p className="eyebrow">About Gold Finder</p><h2>Built for calm, informed exploration.</h2></div><div><p>Gold Finder is an independent discovery interface for physical gold products currently returned by the visitor’s local Amazon marketplace. It is not a dealer, broker or financial adviser.</p><p id="disclosure"><strong>Affiliate disclosure.</strong> As an Amazon Associate, Gold Finder earns from qualifying purchases. Every Amazon advertising link uses the PartnerNet ID assigned to the visitor’s local marketplace. Product facts, images, prices and availability are supplied by Amazon&apos;s Creators API and can change.</p><p id="privacy"><strong>Privacy.</strong> Search and filter choices are reflected in the page URL. Read our <a href="/datenschutz">Privacy Policy / Datenschutz</a> for hosting, contact and affiliate-link information.</p></div></section>
  <section className="faq" id="faq"><p className="eyebrow">FAQ</p><h2>Answers without the sales pitch.</h2><details><summary>Does Gold Finder sell gold?</summary><p>No. It helps visitors explore products and continue to external dealer or mint pages.</p></details><details><summary>Are the prices live?</summary><p>Prices are shown only when the selected Amazon marketplace supplies a current price through its Creators API. Amazon&apos;s offer at checkout is authoritative.</p></details><details><summary>Is this financial advice?</summary><p>No. Gold can rise or fall in value. Consider your circumstances, costs, taxes and independent professional advice.</p></details></section>
  <footer><a className="brand" href="#top"><BrandLogo/></a><p>Independent discovery for physical gold.</p><div><a href="#disclosure">Affiliate disclosure</a><a href="/impressum">Legal Notice / Impressum</a><a href="/datenschutz">Privacy / Datenschutz</a><a href="#faq">FAQ</a><a href="/how-gold-finder-works">Methodology</a><a href="/editorial-policy">Editorial policy</a></div><small>© {new Date().getFullYear()} Gold Finder. Information only; no investment advice.</small></footer>
 </main>
}
function Select({label,icon,value,set,options}:{label:string;icon:React.ReactNode;value:string;set:(v:string)=>void;options:string[]}){return <label className="select">{icon}<span>{label}<select value={value} onChange={e=>set(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></span></label>}
function FilterChips({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:string[]}){return <fieldset className="filter-group"><legend>{label}</legend><div>{options.map(option=><button type="button" key={option} className={value===option?'active':''} aria-pressed={value===option} onClick={()=>set(option)}>{option}</button>)}</div></fieldset>}
function matchesWeight(text:string,weight:string){if(weight==='All')return true;const value=text.toLowerCase().replaceAll(',','.');if(weight==='Up to 1 g')return /(?:0\.1|0\.25|0\.5|1)\s*(?:g|gramm)\b/.test(value)||/1\/\d+\s*(?:oz|unze)/.test(value);if(weight==='2–5 g')return /(?:2|2\.5|3|3\.11|4|5)\s*(?:g|gramm)\b/.test(value);if(weight==='10–20 g')return /(?:10|20)\s*(?:g|gramm)\b/.test(value);return /(?:1|2|5|10)\s*(?:oz|unze)\b|(?:31\.1|50|100|250|500|1000)\s*(?:g|gramm)\b/.test(value)}
function Guide({n,title,text}:{n:string;title:string;text:string}){return <article><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div><BookOpen/></article>}
