'use client';
import {useEffect,useMemo,useState} from 'react';
import Image from 'next/image';
import {Search,SlidersHorizontal,Scale,ShieldCheck,ArrowUpRight,Check,Menu,X,ChevronDown,BookOpen} from 'lucide-react';
import type {AmazonProduct,Marketplace,ProductResponse} from '@/lib/types';

const markets={de:{label:'Germany',amazon:'Amazon.de',currency:'Euro'},us:{label:'United States',amazon:'Amazon.com',currency:'US dollar'},uk:{label:'United Kingdom',amazon:'Amazon.co.uk',currency:'British pound'}} as const;

const sources=[
 ['The Royal Mint','https://www.royalmint.com/invest/bullion/','Product formats, weights and purchase flow'],
 ['GOLD.DE','https://www.gold.de/kaufen/','Comparison structure and dealer transparency'],
 ['APMEX','https://www.apmex.com/category/10000/gold','International product taxonomy'],
 ['BullionByPost','https://www.bullionbypost.co.uk/gold/','Weight-led browsing and product ranges']
];
export default function GoldFinder(){
 const [market,setMarket]=useState<Marketplace>('de'); const [products,setProducts]=useState<AmazonProduct[]>([]); const [live,setLive]=useState(false); const [loading,setLoading]=useState(true); const [message,setMessage]=useState('Loading current marketplace products…');
 const [query,setQuery]=useState(''); const [type,setType]=useState('All'); const [sort,setSort]=useState('name'); const [compare,setCompare]=useState<string[]>([]); const [mobile,setMobile]=useState(false);
 useEffect(()=>{const p=new URLSearchParams(location.search);setQuery(p.get('q')||'');setType(p.get('type')||'All');const selected=p.get('market');if(selected==='de'||selected==='us'||selected==='uk')setMarket(selected)},[]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setProducts([]);setCompare([]);fetch(`/api/products?market=${market}`,{signal:controller.signal}).then(r=>r.json()).then((data:ProductResponse)=>{setProducts(data.products);setLive(data.live);setMessage(data.message||'');setLoading(false)}).catch(e=>{if(e.name!=='AbortError'){setProducts([]);setLive(false);setMessage('Amazon live products are temporarily unavailable. No cached prices are being shown.');setLoading(false)}});return()=>controller.abort()},[market]);
 useEffect(()=>{const p=new URLSearchParams();if(query)p.set('q',query);if(type!=='All')p.set('type',type);if(market!=='de')p.set('market',market);history.replaceState(null,'',`${location.pathname}${p.size?'?'+p:''}`)},[query,type,market]);
 const visible=useMemo(()=>products.filter(p=>(type==='All'||(type==='Bar'?/bar|barren/i.test(p.title):/coin|münze|krugerrand|krügerrand|britannia|maple leaf|philharmoniker/i.test(p.title)))&&(p.title+p.brand+p.model+p.features.join(' ')).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='price'?(a.price?.amount??Infinity)-(b.price?.amount??Infinity):a.title.localeCompare(b.title)),[products,query,type,sort]);
 const toggle=(id:string)=>setCompare(c=>c.includes(id)?c.filter(x=>x!==id):c.length<4?[...c,id]:c);
 return <main>
  <header><a className="brand" href="#top"><span>AU</span> GOLD FINDER</a><nav className={mobile?'open':''}><a href="#finder">Finder</a><a href="#guide">Buying guide</a><a href="#dealers">Dealers</a><a href="#about">About</a></nav><button className="menu" aria-label="Menu" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></header>
  <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">Independent bullion discovery</p><h1>Find your gold.<br/><em>Invest with clarity.</em></h1><p>Explore recognised bars and coins, understand the trade-offs, then continue to a verified dealer page.</p><a className="button light" href="#finder">Start exploring <ArrowUpRight size={17}/></a></div></section>
  <section className="finder" id="finder"><div className="finder-intro"><p className="eyebrow">Gold finder</p><h2>A clearer way to explore physical gold.</h2><p>Select a marketplace to load its own Amazon catalogue, local product language, currency, availability and partner links.</p></div>
   <div className="market-switcher" role="group" aria-label="Amazon marketplace">{(Object.keys(markets) as Marketplace[]).map(id=><button key={id} className={market===id?'active':''} onClick={()=>setMarket(id)}><span>{id==='de'?'DE':id==='us'?'US':'UK'}</span>{markets[id].label}</button>)}</div><div className="controls"><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search product, brand or feature"/></label><Select label="Format" icon={<SlidersHorizontal/>} value={type} set={setType} options={['All','Bar','Coin']}/><Select label="Sort" icon={<ChevronDown/>} value={sort} set={setSort} options={['name','price']}/></div>
   <div className="result-head"><span>{loading?'Loading local catalogue…':live?`${visible.length} currently available models on ${markets[market].amazon}`:'Live selection unavailable'}</span><button onClick={()=>{setQuery('');setType('All')}}>Reset filters</button></div>
   {!loading&&!live&&<div className="api-status"><strong>Live Amazon data unavailable</strong><p>{message}</p></div>}
   <div className="grid">{visible.map((p,i)=><article className="card" key={p.asin}><div className="product-image"><Image src={p.image} alt={p.title} fill sizes="(max-width: 590px) 90vw, (max-width: 900px) 45vw, 30vw"/><span>{String(i+1).padStart(2,'0')}</span></div><div className="card-body"><div className="tag">{markets[market].amazon} · ASIN {p.asin}</div><h3>{p.title}</h3><dl><div><dt>Brand</dt><dd>{p.brand}</dd></div><div><dt>Model</dt><dd>{p.model}</dd></div><div><dt>Availability</dt><dd>{p.availability}</dd></div><div><dt>Parent ASIN</dt><dd>{p.parentAsin}</dd></div></dl>{p.features.length>0&&<ul className="features">{p.features.slice(0,3).map(feature=><li key={feature}>{feature}</li>)}</ul>}<p className={p.price?'live-price':'no-price'}>{p.price?.display||`Current ${markets[market].currency} price not supplied by Amazon`}</p><div className="actions"><a className="amazon" href={p.detailPageUrl} target="_blank" rel="nofollow sponsored noopener">Advertising link · View on Amazon <ArrowUpRight size={15}/></a><button className={compare.includes(p.asin)?'selected':''} onClick={()=>toggle(p.asin)}>{compare.includes(p.asin)?<Check size={14}/>:<Scale size={14}/>} Compare</button></div></div></article>)}</div>
   <p className="amazon-note">Prices and availability can change at any time. The product detail page and offer shown by {markets[market].amazon} at the time of purchase are authoritative. All Amazon links are advertising links.</p>
   {!visible.length&&<div className="empty"><Search/><h3>No matches yet</h3><p>Try another region or remove a filter.</p></div>}
  </section>
  {compare.length>0&&<aside className="compare"><div><Scale/><strong>Compare selection</strong><span>{compare.length}/4 products</span></div><div>{compare.map(id=><button key={id} onClick={()=>toggle(id)}>{products.find(p=>p.asin===id)?.title}<X size={13}/></button>)}</div><a href="#comparison">Review comparison</a></aside>}
  <section className="comparison" id="comparison"><p className="eyebrow">Side by side</p><h2>Your selected gold</h2>{compare.length?<div className="compare-grid">{compare.map(id=>{const p=products.find(x=>x.asin===id)!;return p&&<article key={id}><h3>{p.title}</h3><p>{p.brand} · {p.model}</p><p>{p.price?.display||`No current ${markets[market].currency} price`}</p><p>ASIN {p.asin}</p><a href={p.detailPageUrl} target="_blank" rel="nofollow sponsored noopener">Advertising link · Amazon <ArrowUpRight size={14}/></a></article>})}</div>:<p className="muted">Choose up to four products in the finder to compare their current Amazon data.</p>}</section>
  <section className="guide" id="guide"><div><p className="eyebrow">Buying guide</p><h2>Know what you are comparing.</h2><p>Physical gold is simple in principle, but size, premium, delivery and storage all shape the final decision.</p><a href="https://www.royalmint.com/invest/discover/invest-in-gold/an-introduction-to-investing-in-precious-metals-what-are-my-options/" target="_blank">Read the source guide <ArrowUpRight size={15}/></a></div><div className="guide-list"><Guide n="01" title="Bars or coins?" text="Bars often concentrate value efficiently. Coins may offer recognisable designs and more flexible resale sizes."/><Guide n="02" title="Weight and fineness" text="One troy ounce equals 31.1035 grams. Fineness describes the proportion of pure gold in the item."/><Guide n="03" title="Premium and total cost" text="Compare fabrication premiums, insured delivery, payment fees and any applicable local taxes—not only the metal value."/><Guide n="04" title="Storage and exit" text="Plan secure storage, insurance and a resale route before buying. Terms differ by dealer and country."/></div></section>
  <section className="trust" id="dealers"><ShieldCheck/><div><p className="eyebrow">Source-led by design</p><h2>Clarity before clicks.</h2></div><p>We do not invent ratings, prices or partnerships. Dealer links point to public source pages. Amazon search links are clearly marked as affiliate links; sponsored status never determines the displayed product facts.</p></section>
  <section className="sources"><p className="eyebrow">Research references</p><h2>What shaped this first release.</h2><div>{sources.map(s=><a key={s[0]} href={s[1]} target="_blank"><strong>{s[0]}</strong><span>{s[2]}</span><ArrowUpRight/></a>)}</div></section>
  <section className="about" id="about"><div><p className="eyebrow">About Gold Finder</p><h2>Built for calm, informed exploration.</h2></div><div><p>Gold Finder is an independent discovery interface for physical gold products currently returned by the selected local Amazon marketplace. It is not a dealer, broker or financial adviser.</p><p id="disclosure"><strong>Affiliate disclosure.</strong> As an Amazon Associate, Gold Finder earns from qualifying purchases. Amazon advertising links use the local PartnerNet ID: Onlinestarkei-21 for Germany, goldfindercom-20 for the United States and goldfindercom-21 for the United Kingdom. Product facts, images, prices and availability are supplied by Amazon&apos;s Creators API and can change.</p><p id="privacy"><strong>Privacy.</strong> Search and filter choices are reflected in the page URL. Read our <a href="/datenschutz">Privacy Policy / Datenschutz</a> for hosting, contact and affiliate-link information.</p></div></section>
  <section className="faq" id="faq"><p className="eyebrow">FAQ</p><h2>Answers without the sales pitch.</h2><details><summary>Does Gold Finder sell gold?</summary><p>No. It helps visitors explore products and continue to external dealer or mint pages.</p></details><details><summary>Are the prices live?</summary><p>Prices are shown only when the selected Amazon marketplace supplies a current price through its Creators API. Amazon&apos;s offer at checkout is authoritative.</p></details><details><summary>Is this financial advice?</summary><p>No. Gold can rise or fall in value. Consider your circumstances, costs, taxes and independent professional advice.</p></details></section>
  <footer><a className="brand" href="#top"><span>AU</span> GOLD FINDER</a><p>Independent discovery for physical gold.</p><div><a href="#disclosure">Affiliate disclosure</a><a href="/impressum">Legal Notice / Impressum</a><a href="/datenschutz">Privacy / Datenschutz</a><a href="#faq">FAQ</a></div><small>© {new Date().getFullYear()} Gold Finder. Information only; no investment advice.</small></footer>
 </main>
}
function Select({label,icon,value,set,options}:{label:string;icon:React.ReactNode;value:string;set:(v:string)=>void;options:string[]}){return <label className="select">{icon}<span>{label}<select value={value} onChange={e=>set(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></span></label>}
function Guide({n,title,text}:{n:string;title:string;text:string}){return <article><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div><BookOpen/></article>}
