import type {Metadata} from 'next';
import {manufacturerProducts,manufacturerPath,productFamily} from '@/lib/manufacturer-products';
import BrandLogo from './BrandLogo';
import ProductOffers from './ProductOffers';
import {origin,markets,regions,products,productPath,productAlternates,hubAlternates,ui,regionalCopy,reviewed,type Region,type Product} from '@/lib/product-catalogue';

export function productMetadata(product:Product,region:Region):Metadata{
 const market=markets[region],language=market.language,name=product.name[language],country=market.country;
 const title=language==='de'?`${name}: Größen, Kauf & Vergleich | Gold Finder`:language==='fr'?`${name} : achat et comparaison en France | Gold Finder`:`${name}: buying & comparison · ${country} | Gold Finder`;
 const description=language==='de'?`${name} für Deutschland: Produktmerkmale, Größenvergleich, Kosten je Gramm und Bezugsquellen. Gewicht und konkrete Ausführung vor dem Kauf prüfen.`:language==='fr'?`${name} en France : caractéristiques, comparaison des formats, coût par gramme et sources officielles. Vérifiez l’édition et les conditions de livraison.`:`Compare ${name} for ${country}: specifications, size trade-offs, cost per gram and buying sources. Check the exact edition and delivered total.`;
 return{title,description,alternates:{canonical:productPath(product,region),languages:productAlternates(product)},robots:{index:true,follow:true,'max-snippet':-1,'max-image-preview':'large'},openGraph:{title,description,type:'website',url:productPath(product,region),locale:market.hreflang.replace('-','_'),siteName:'Gold Finder'},twitter:{card:'summary',title,description}};
}
export function hubMetadata(region:Region):Metadata{const m=markets[region],t=ui[m.language];return{title:`${t.catalogue} · ${m.country} | Gold Finder`,description:t.guideIntro,alternates:{canonical:m.hub,languages:hubAlternates()},openGraph:{title:`${t.catalogue} · ${m.country}`,description:t.guideIntro,url:m.hub,locale:m.hreflang.replace('-','_')}};}
function LanguageLinks({region,product}:{region:Region;product?:Product}){return <nav className="market-links" aria-label={ui[markets[region].language].languages}>{regions.map(r=><a key={r} href={product?productPath(product,r):markets[r].hub} hrefLang={markets[r].hreflang} aria-current={r===region?'page':undefined}>{markets[r].label}</a>)}</nav>;}
function Header({region}:{region:Region}){const m=markets[region],t=ui[m.language];return <header className="seo-header"><a className="brand" href={m.hub}><BrandLogo/></a><a href={m.hub}>{t.all} →</a></header>;}
function Footer({region}:{region:Region}){const m=markets[region],t=ui[m.language];return <footer><a className="brand" href={m.hub}><BrandLogo/></a><p>{t.disclosure}</p><div><a href={m.hub}>{t.all}</a><a href="/impressum">{t.legal}</a><a href="/datenschutz">{t.privacy}</a></div><small>© 2026 Gold Finder. {t.info}</small></footer>;}
const json=(value:unknown)=>JSON.stringify(value).replace(/</g,'\\u003c');
export function ProductHub({region}:{region:Region}){const m=markets[region],t=ui[m.language];const graph={'@context':'https://schema.org','@type':'CollectionPage',name:`${t.catalogue} · ${m.country}`,url:`${origin}${m.hub}`,inLanguage:m.hreflang,mainEntity:{'@type':'ItemList',itemListElement:products.map((p,i)=>({'@type':'ListItem',position:i+1,name:p.name[m.language],url:`${origin}${productPath(p,region)}`}))}};return <main className="seo-page" lang={m.hreflang}><Header region={region}/><article><script type="application/ld+json" dangerouslySetInnerHTML={{__html:json(graph)}}/><p className="eyebrow">{m.country} · Gold Finder</p><h1>{t.catalogue}</h1><p className="seo-intro">{t.guideIntro}</p><LanguageLinks region={region}/><p>{regionalCopy[region].intro}</p>{(['bar','coin'] as const).map(kind=><section className="directory-group" key={kind}><h2>{kind==='bar'?t.bars:t.coins}</h2><div className="directory-links">{products.filter(p=>p.kind===kind).map(p=><a key={p.id} href={productPath(p,region)}><strong>{p.name[m.language]}</strong><span>{p.size} · {m.country}</span></a>)}</div></section>)}<section className="directory-group"><h2>{m.language==='de'?'Einzelne Herstellerartikel':m.language==='fr'?'Articles de fabricants':'Individual manufacturer products'}</h2><div className="directory-links">{manufacturerProducts.map(p=><a key={p.slug} href={manufacturerPath(p,region)}><span>{p.brand}</span><strong>{p.name[m.language]}</strong></a>)}</div></section></article><Footer region={region}/></main>;}
export default function ProductLanding({product,region}:{product:Product;region:Region}){
 const m=markets[region],l=m.language,t=ui[l],regional=regionalCopy[region],name=product.name[l],url=`${origin}${productPath(product,region)}`;
 const format=(n:number,max=4)=>new Intl.NumberFormat(m.locale,{maximumFractionDigits:max}).format(n);
 const gramWeight=format(product.grams),ounces=format(product.grams/31.1035);
 const cost=l==='de'?`Teile den vollständigen Kaufpreis durch das ausgewiesene Feingoldgewicht. Rechenbeispiel mit frei gewählten Zahlen, kein Marktpreis: Bei 100 EUR je Gramm Feingold ergeben ${gramWeight} g einen rechnerischen Metallwert von ${format(product.grams*100,2)} EUR. Versand und Aufgeld kommen in einem echten Angebot hinzu. Gilt das Nenngewicht als Bruttogewicht, muss zunächst der Feingoldanteil berechnet werden.`:l==='fr'?`Divisez le prix total livré par le poids d’or fin déclaré. Exemple fictif, sans valeur de cotation : à 100 EUR par gramme d’or fin, ${gramWeight} g représentent une valeur métallique théorique de ${format(product.grams*100,2)} EUR. La prime et la livraison s’ajoutent dans une offre réelle. Si le poids indiqué est brut, calculez d’abord le poids d’or fin.`:`Divide the delivered price by declared fine-gold weight. Illustrative arithmetic, not a market quote: at 100 ${m.currency} per gram of fine gold, ${gramWeight} g gives a hypothetical metal value of ${format(product.grams*100,2)} ${m.currency}. A real offer adds a premium and delivery. If the stated weight is gross weight, calculate fine-gold weight first.`;
 const weightAnswer=l==='de'?`Die Referenzgröße beträgt ${product.size}, entsprechend rund ${gramWeight} g beziehungsweise ${ounces} Feinunzen. Bei Münzen bezieht sich diese Vergleichsgröße auf die 1-oz-Ausgabe; andere Stückelungen sind eigene Varianten. Gewicht und Feingehalt im Angebot bleiben maßgeblich.`:l==='fr'?`Le format de référence est ${product.size}, soit environ ${gramWeight} g ou ${ounces} once(s) troy. Pour les pièces, cette référence concerne l’édition d’une once ; les fractions sont des variantes distinctes. Vérifiez toujours le poids et le titre de l’offre.`:`The reference size is ${product.size}, approximately ${gramWeight} g or ${ounces} troy ounces. For coins, this comparison refers to the 1 oz edition; fractional sizes are separate variants. Always verify the listing’s weight and fineness.`;
 const faqs=[{q:l==='de'?`Welches Gewicht hat ${name}?`:l==='fr'?`Quel est le poids de ce produit : ${name} ?`:`What is the weight of a ${name}?`,a:weightAnswer},{q:t.priceFaq,a:t.priceAnswer},{q:t.authFaq,a:t.authAnswer}];
 const graph={'@context':'https://schema.org','@graph':[
 {'@type':'WebPage','@id':url,name,description:product.detail[l],url,inLanguage:m.hreflang,dateModified:reviewed,about:{'@type':'Thing',name},publisher:{'@type':'Organization',name:'Gold Finder',url:origin}},
 {'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:t.catalogue,item:`${origin}${m.hub}`},{'@type':'ListItem',position:2,name,item:url}]},
 {'@type':'FAQPage',inLanguage:m.hreflang,mainEntity:faqs.map(f=>({'@type':'Question',name:f.q,acceptedAnswer:{'@type':'Answer',text:f.a}}))}
 ]};
 const related=products.filter(p=>p.kind===product.kind&&p.id!==product.id).sort((a,b)=>Math.abs(a.grams-product.grams)-Math.abs(b.grams-product.grams)).slice(0,4);
 return <main className="seo-page product-landing" lang={m.hreflang}><Header region={region}/><article>
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html:json(graph)}}/>
 <nav className="breadcrumbs" aria-label={t.all}><a href={m.hub}>{t.catalogue}</a><span>/</span><span>{name}</span></nav>
 <p className="eyebrow">{m.country} · {product.kind==='bar'?t.bars:t.coins}</p><h1>{name}</h1><p className="seo-intro">{product.detail[l]}</p><LanguageLinks region={region} product={product}/>
 <div className="direct-answer"><strong>{t.quick}</strong><p>{product.comparison[l]}</p></div><a className="seo-cta" href="#offers">{t.offers} ↓</a><p className="updated">{t.reviewed}: <time dateTime={reviewed}>{new Intl.DateTimeFormat(m.locale,{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${reviewed}T12:00:00Z`))}</time></p>
 <section className="key-facts"><h2>{t.facts}</h2><dl className="product-specs"><div><dt>{t.weight}</dt><dd>{product.size} · ≈ {gramWeight} g · ≈ {ounces} oz t</dd></div><div><dt>{t.type}</dt><dd>{product.kind==='bar'?t.bar:t.coin}</dd></div><div><dt>{t.purity}</dt><dd>{t.purityValue}</dd></div></dl><p>{t.note}</p></section>
 <section className="seo-section"><h2>{t.compare}</h2><p>{weightAnswer} {product.comparison[l]}</p></section>
 <section className="seo-section"><h2>{t.cost}</h2><div><p>{cost}</p><p>{regional.unit}</p></div></section>
 <section className="seo-section"><h2>{t.region}{l==='en'?` · ${m.country}`:''}</h2><div><p>{regional.intro}</p><p>{regional.delivery}</p></div></section>
 {manufacturerProducts.some(p=>productFamily(p)?.id===product.id)&&<section className="directory-group"><h2>{l==='de'?'Herstellerartikel in dieser Größe':l==='fr'?'Articles dans ce format':'Products in this size'}</h2><div className="directory-links">{manufacturerProducts.filter(p=>productFamily(p)?.id===product.id).map(p=><a key={p.slug} href={manufacturerPath(p,region)}><span>{p.brand}</span><strong>{p.name[l]}</strong></a>)}</div></section>}
 <section className="product-offers" id="offers"><h2>{t.offers}</h2><p>{regional.offerNote}</p><ProductOffers region={region} productId={product.id}/></section>
 <section className="seo-faq"><h2>{t.faq}</h2>{faqs.map(f=><details key={f.q}><summary>{f.q}</summary><p>{f.a}</p></details>)}</section>
 <section className="seo-sources"><h2>{t.sources}</h2><a href={product.source.url} target="_blank" rel="noopener noreferrer">{product.source.name} ↗</a>{region==='uk'&&<a href="https://www.gov.uk/guidance/gold-acquisitions-imports-investments-and-vat-notice-70121" target="_blank" rel="noopener noreferrer">HMRC — Investment gold ↗</a>}</section>
 <aside className="related"><h2>{t.related}</h2><div>{related.map(p=><a key={p.id} href={productPath(p,region)}><span>{m.country}</span><strong>{p.name[l]}</strong><span>→</span></a>)}</div><a className="all-guides" href={m.hub}>{t.all} →</a></aside>
 </article><Footer region={region}/></main>;
}
