import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {ArrowRight,CheckCircle2,ExternalLink} from 'lucide-react';
import {findSeoPage,seoPages} from '@/lib/seo-pages';

type Props={params:Promise<{slug:string[]}>};
export function generateStaticParams(){return seoPages.map(page=>({slug:page.slug}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const page=findSeoPage((await params).slug);if(!page)return{};const path=`/${page.slug.join('/')}`,isMarket=['us','uk','de'].includes(page.slug[0]);return{title:page.title,description:page.description,alternates:{canonical:path,...(isMarket?{languages:{'en-US':'/us/buy-gold','en-GB':'/uk/buy-gold','de-DE':'/de/gold-kaufen','x-default':'/guides/gold-bars-vs-coins'}}:{})},openGraph:{title:page.title,description:page.description,url:path,type:'article',siteName:'Gold Finder'},twitter:{card:'summary_large_image',title:page.title,description:page.description}}}

export default async function SeoLanding({params}:Props){const page=findSeoPage((await params).slug);if(!page)notFound();const path=`https://www.gold-finder.com/${page.slug.join('/')}`;const graph={'@context':'https://schema.org','@graph':[{'@type':'Article',headline:page.headline,description:page.description,dateModified:'2026-09-14',mainEntityOfPage:path,author:{'@type':'Organization',name:'Gold Finder'},publisher:{'@type':'Organization',name:'Gold Finder',url:'https://www.gold-finder.com'}},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Gold Finder',item:'https://www.gold-finder.com'},{'@type':'ListItem',position:2,name:page.headline,item:path}]},{'@type':'FAQPage',mainEntity:page.faqs.map(f=>({'@type':'Question',name:f.q,acceptedAnswer:{'@type':'Answer',text:f.a}}))}]};return <main className="seo-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(graph)}}/><header className="seo-header"><a className="brand" href="/"><span>AU</span> GOLD FINDER</a><a href="/#finder">Open product finder <ArrowRight size={16}/></a></header><article><nav className="breadcrumbs" aria-label="Breadcrumb"><a href="/">Gold Finder</a><span>/</span><span>{page.headline}</span></nav><p className="eyebrow">{page.eyebrow}</p><h1>{page.headline}</h1><p className="seo-intro">{page.intro}</p><div className="direct-answer"><strong>Quick answer</strong><p>{page.answer}</p></div><a className="seo-cta" href={`/?q=${encodeURIComponent(page.query)}#finder`}>{page.cta}<ArrowRight size={17}/></a><p className="updated">Reviewed {page.updated}</p><section className="key-facts"><h2>What to know first</h2><div>{page.facts.map(f=><p key={f}><CheckCircle2/>{f}</p>)}</div></section>{page.sections.map(section=><section className="seo-section" key={section.heading}><h2>{section.heading}</h2><p>{section.body}</p></section>)}<section className="seo-faq"><p className="eyebrow">Questions answered</p><h2>Frequently asked questions</h2>{page.faqs.map(f=><details key={f.q}><summary>{f.q}</summary><p>{f.a}</p></details>)}</section><section className="seo-sources"><h2>Primary sources</h2><p>Use these official references to check specifications and rules that may change.</p>{page.sources.map(source=><a href={source.url} target="_blank" rel="noopener" key={source.url}>{source.name}<ExternalLink size={15}/></a>)}</section><aside className="related"><h2>Continue exploring</h2><div>{seoPages.filter(p=>p!==page).slice(0,3).map(p=><a key={p.slug.join('/')} href={`/${p.slug.join('/')}`}><span>{p.eyebrow}</span><strong>{p.headline}</strong><ArrowRight/></a>)}</div></aside></article><footer><a className="brand" href="/"><span>AU</span> GOLD FINDER</a><p>Independent discovery for physical gold.</p><div><a href="/impressum">Legal Notice</a><a href="/datenschutz">Privacy</a></div><small>© {new Date().getFullYear()} Gold Finder. Information only; no investment advice.</small></footer></main>}
